---
title: "Ensaio clínico randomizado:"
subtitle: "efeito da droga vegetal de *Eclipta prostrata* (L.) L. (*Asteraceae*) no ângulo de fase em adultos com obesidade grau I"
author: "Gustavo Santos Paiva Laender Moura"
institute: "Faculdade de Medicina de Ribeirão Preto - USP"
date: "2025"
output:
  xaringan::moon_reader: # new kind of output!
    css: 
      - default # default xaringan theme CSS file
      - css/nhsr.css # custom primary CSS file
      - css/nhsr-fonts.css # custom font CSS file
    lib_dir: libs # creates directory for libraries
    seal: false # false: mean you have to choose a custom title slide
    # seal: true creates a title slide with inverse colors using metadata from your YAML
    nature:
      highlightStyle: googlecode # highlighting syntax for code
        # Other highlightStyle options from remark.js are: arta, ascetic, dark, default, far, github, googlecode, idea, ir-black, magula, monokai, rainbow, solarized-dark, solarized-light, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eighties, vs, zenburn.
        # [https://github.com/gnab/remark/wiki/Configuration#highlighting].
      highlightLines: true # true: enables code line highlighting 
      highlightLanguage: ["r"] # languages to highlight
      countIncrementalSlides: true # false: disables counting of incremental slides
      ratio: "16:9" # 4:3 for standard size
    includes:
      after_body: [css/insert-logo.html] # html file that adds NHS logo to slides
---

```{r setup, include = FALSE}
library(xaringan)
library(knitr)
library(tidyverse)
library(NHSRtheme)
# set default options
opts_chunk$set(echo = FALSE,
               fig.width = 7.252,
               fig.height = 4,
               dpi = 300)

# uncomment the following lines if you want to use the NHS-R theme colours by default
scale_fill_continuous <- partial(scale_fill_nhs, discrete = FALSE)
scale_fill_discrete <- partial(scale_fill_nhs, discrete = TRUE)
scale_colour_continuous <- partial(scale_colour_nhs, discrete = FALSE)
scale_colour_discrete <- partial(scale_colour_nhs, discrete = TRUE)
```

class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

---
class: inverse, middle, center

# Justificativa
____
---
name: Justificativa
# Justificativa

--

* first point

--

* second point

--

* third point

---
template: Justificativa

---

template: Justificativa

---
class: inverse, middle, center

# Hipótese
____
---
class: middle, left
# Hipótese
----

Em indivíduos com .my-coral[obesidade grau I] submetidos ao tratamento convencional para perda de peso com intervenção nutricional, a administração da **droga vegetal de _Eclipta prostrata_**, na dose de `750 mg por via oral, três vezes ao dia`, durante um período de `3 meses`, resulta em um aumento estatisticamente significativo do ângulo de fase em comparação com o grupo placebo.

---
class: inverse, middle, center

# Objetivos
____
---
name: objetivos
# Objetivos
---
template: objetivos
## Objetivo geral

Avaliar a atividade anti-inflamatória da **droga vegetal de _Eclipta prostrata_** em indivíduos com .my-coral[obesidade grau I] submetidos ao tratamento convencional para perda de peso com intervenção nutricional, por meio do impacto no ângulo de fase derivado da análise de impedância bioelétrica, em comparação ao placebo.

---
template: objetivos
## Objetivos específicos
### Descrever o perfil epidemiológico
1. idade;
1. sexo; 
1. etnia autodeclarada;
1. hábitos de vida: tabagismo, etilismo, atividade física e hábitos alimentares; 
1. comorbidades e medicamentos de uso contínuo.

---
template: objetivos
## Objetivos específicos
### Desfecho primário:
Avaliar o efeito da **droga vegetal de _Eclipta prostrata_** no(a):
1. ângulo de fase derivado da análise de impedância bioelétrica corporal e 
1. proteína C reativa sérica.

---
template: objetivos
## Objetivos específicos
### Avaliar a segurança da intervenção
1. Parâmetros clínicos
1. Monitorizar sinais de toxicidade assintomática, através de acompanhamento de: AST, ALT, GGT, FALC, bilirrubinas totais e frações, amilase, albumina, ureia, creatinina, CPK, ácido úrico, amilase, sódio, potássio, cálcio e hemograma e eletrocardiograma.
---
template: objetivos
## Objetivos específicos
### Desfechos exploratórios
#### Efeito da **droga vegetal de _Eclipta prostrata_** em: 
1. pressão arterial sistêmica, 
1. lipídios séricos (colesterol total, LDL-c, HDL-c, triglicerídeos)
1. perfil glicêmico (glicemia de jejum, hemoglobina glicosilada).

---
class: inverse, middle, center
# Materiais e Métodos
____
---
name: Metodologia
# Metodologia
---
template: Metodologia
## Aspectos Éticos

- **Aprovação Ética:** Comitê de Ética em Pesquisa da FMRP-USP  
  
- **Boas Práticas para Pesquisa Clínicas**
  ([ICH Guidelines](http://www.ich.org/home.html))
  
- **Registro do Estudo na plataforma REBEC  **
  
- **Acesso ao Patrimônio Genético** da *Eclipta prostrata*  conforme a Lei nº 13.123/2015 (Atestado de Regularidade de Acesso nº A7CDD30)

---
template: Metodologia
## Determinação da Dose
###Droga Vegetal de *Eclipta Prostrata*

- **Regulação:** Ensaios clínicos devem utilizar a mesma dose e posologia do .my-coral[uso tradicional] .small[[ANVISA (2014), MS (2008) e WHO (2005)]].

- **Uso Tradicional (Ayurveda):** A dose tradicional para *Eclipta prostrata* é de 2 a 3 g/dia, administrada de forma fracionada .small[(Kambli; Khaires; Kushwaha, 2022)].

---
template: Metodologia
## Determinação da Dose
###Droga Vegetal de *Eclipta Prostrata*

- **Ensaios Clínicos Anteriores:**  
  - Rangineni; Sharada; Saxena (2007) utilizaram 3 g/dia;  
  - Hasan et al. (2013) e Sazia et al. (2015a, 2015b) utilizaram 2,4 g/dia.

- **Dose Adotada no Estudo:** 750 mg, 3 vezes ao dia (totalizando 2250 mg/dia), administrada com café da manhã, almoço e jantar.

---
template: Metodologia
## Determinação da Dose
###Droga Vegetal de *Eclipta Prostrata*

- **Equivalência à Dose Máxima Recomendada:** 2250 mg/dia corresponde a 13,8% da dose máxima recomendada para ensaios clínicos em humanos, baseada em estudos de toxicidade animal .small[(FDA, 2005)].
---
template: Metodologia
## Cálculo do Tamanho Amostral

- **Dados Populacionais:**  
  Banco de dados de 214.732 adultos na Alemanha: ângulo de fase estratificados por idade, sexo e IMC.  
  .red[_Indivíduos com ângulo de fase abaixo do percentil 10 apresentaram proteína C reativa significativamente elevada_.]</br> .small[(BOSY-WESTPHAL et al., 2006)].

- **População Brasileira:**  
  Resultados semelhantes em estudo com 2122 indivíduos, dos quais 478 tinham IMC > 30 kg/m² .small[(MATTIELLO; MUNDSTOCK; ZIEGELMANN, 2022)].

---
template: Metodologia
## Cálculo do Tamanho Amostral
### Ângulo de fase
- **Relação entre Média e Percentil 10:**  
  A média populacional do AF é 15% maior que o valor do AF correspondente ao percentil 10, com diferença média de 0,84° .small[(0,78° para mulheres e 0,89° para homens)].

- **Premissa de Benefício Clínico:**  
  Consideramos clinicamente relevante um incremento de 0,28° (um terço de 0,84°) associado a intervenção.

---
template: Metodologia

## Cálculo do Tamanho Amostral

### Ângulo de fase

- **Parâmetros para o Cálculo:**  
  - Grupo _Eclipta_: incremento médio de 0,28°;  
  - Grupo placebo: incremento médio de 0,14° .small[(50% do incremento do grupo DVEP, devido ao efeito placebo e Hawthorne)];  
  - Desvio padrão médio: 0,21°.

- **Tamanho Amostral:**  
  Com nível de significância de 0,05 (bicaudal) e poder de 80%, obteve-se um tamanho amostral de 37 participantes por grupo .small[(SINGER, 2001)].

---
template: Metodologia

## Gestão de Dados

**Plano de Gestão de Dados:** DMPTool usando o template Digital Curation Centre.  
  [Plano completo](https://doi.org/10.48321/D1N34D) .small[(APÊNDICE A)].

**Plataforma de Coleta:** Instância FMRP do REDCap.

**Estrutura dos Projetos REDCap:**  
- **Projeto Principal (PID 1958):** 34 instrumentos de coleta e 821 campos .small[(APÊNDICE C)]

---
template: Metodologia

## Gestão de Dados
**Projetos Adicionais:**
- PID 2184: Para o público verificar elegibilidade .small[(APÊNDICE D)];
- PID 2246: Para avaliação completa de elegibilidade pela equipe de pesquisa .small[(APÊNDICE E)];
- PID 2205: Suporte operacional com códigos do NCIT para indexação de comorbidades e medicamentos .small[(APÊNDICE F)].

**Confiabilidade na coleta de dados:**  
  Lógicas condicionais, campos calculados, campos redundantes e alertas para validação de resultados, assegurando a integridade dos dados.

---

---
template: Metodologia
## Protocolo Experimental

- **Tipo de Estudo:** Ensaio clínico de intervenção, fase II, randomizado 1:1, triplo cego, controlado por placebo, com grupos paralelos.
- **Intervenções:**  
  - **Grupo Eclipta Prostrata:** Recebe intervenção nutricional + droga vegetal de *Eclipta prostrata* (2250 mg/dia por 3 meses).  
  - **Grupo Placebo:** Recebe intervenção nutricional + cápsulas de placebo (mesma dose e posologia).  
- **Cegamento:** As cápsulas e frascos são indistinguíveis.
---

class: middle, left
# Critérios de Inclusão e Não-Inclusão

- **Inclusão:**  
  - Participantes adultos (18 a 59 anos) de ambos os gêneros com obesidade grau I, acompanhados pela ESF de Jardinópolis.  
  - Escolha justificada pela alta prevalência e uniformidade necessária para evitar vieses.
  
- **Exclusão Prévia:**  
  - Comorbidades que não sejam as associadas à obesidade (ex.: doenças autoimunes, inflamatórias intestinais, neurodegenerativas, renais, pneumopatias, neoplasias, imunodepressão, e doença periodontal crônica).  
  - Histórico de uso crônico de anti-inflamatórios ou imunossupressores; distúrbios disabsortivos e alterações anatômicas do trato gastrointestinal.  
  - Condições que interfiram na análise de impedância bioelétrica (ex.: insuficiência cardíaca estágio C/D, trombose, amputações, edema, paquidermia, linfedema, lesões cutâneas no local dos eletrodos, modificações recentes de diuréticos, ou uso de dispositivos cardíacos implantáveis).  
  - Participantes com quadros de diarreia crônica ou restrição de liberdade/incapazes de consentir adequadamente.
---

class: middle, left
# Critérios de Exclusão

- Retirada do consentimento.
- Eventos adversos, seja relacionados ou não à pesquisa, conforme deliberação do comitê de monitoramento.
- Mulheres que se tornem gestantes ou desejem engravidar durante o período do estudo.
- Outros eventos imprevistos, segundo o critério do comitê de monitoramento externo.
---

class: middle, left
# Seleção e Recrutamento

- **Parceria Institucional:** Colaboração com a Secretaria de Saúde de Jardinópolis-SP e divulgação via ESF.
- **Procedimento:**  
  - A equipe de pesquisa contata potenciais participantes, fornecendo informações detalhadas (objetivos, métodos, riscos e benefícios) em linguagem acessível.  
  - A elegibilidade é verificada conforme os critérios definidos.
- **Consentimento:**  
  - Obtido de forma livre e esclarecida, conforme a Resolução CNS 466/2012.  
  - O TCLE é preenchido em duas vias (uma para o participante e outra arquivada) e uma cópia digital é salva no REDCap.
---

class: middle, left
# Randomização

- **Geração da Sequência:**  
  - Criada em 03/07/2023 pelo Prof. Dr. Fábio Carmona, utilizando a ferramenta [Sealed Envelope](https://www.sealedenvelope.com/simple-randomiser/v1/lists).  
  - Parâmetros: seed 177782464738902, blocos de tamanho 4 ou 6, lista com 148 itens (alocação 1:1).
  
- **Procedimento:**  
  - A sequência é encaminhada exclusivamente à farmácia para a produção e rotulação dos frascos.  
  - Frascos com cápsulas (droga vegetal ou placebo) são idênticos, diferenciados apenas pelo número de alocação.
  - Participantes são designados por ordem de inclusão (ex.: o primeiro participante recebe o frasco com o número 1).
---
