# Clear existing data and graphics
rm(list=ls())
graphics.off()

# Load necessary libraries
library(Hmisc)
library(tidyverse) 

# Set working directory
setwd("/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/PROJECTS/DVEP")

data <- read.csv("/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/PROJECTS/DVEP/2_Files/Data.csv", header = TRUE)
codebook <- read.csv("/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/PROJECTS/DVEP/2_Files/Codebook.csv", header = TRUE)

# Remove identifying name from record_id
data$record_id <- substr(data$record_id,1,2)

# Renaming Variables
## Create rename vector
rename_vector <- setNames(object = colnames(data), codebook$variable_recoded)
## Apply  rename vector to data
data <- data %>%
    rename(!!!rename_vector)
rm(rename_vector)

## Loop over the variables and assign labels
for (i in seq_along(codebook$variable_recoded)) {
    # Get the variable name in data
    variable_name <- codebook$variable_recoded[i]
    
    # Get the corresponding label
    variable_label <- codebook$label_pt[i]
    
    # Assign the label to the variable in the data
    label(data[[variable_name]]) <- variable_label
}
rm(i, variable_name, variable_label) # Remove intermediate vectors

writeLines(
    names(data), 
    "/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/PROJECTS/DVEP/3_Output/3_Variables.txt")

# Creates list of variables by instrument
instruments <- list(
    redcap = c("event_name", "repeat_instrument", "repeat_instance"),
    elegibility = c("record_id", "date_birth", "age", "ubs", "contact_options", "contact_hours", "contact_days", "transport_research_center", "research_source_info", "availability_comments_yn", "availability_comments", "sex", "pregnant_nursing_yn", "eleg_height", "eleg_weight", "bmi_reported", "eleg_comorbidity_yn", "comorbidity_list", "drug_use_yn", "drug_list", "high_risk_pregnancy_ineffective_contraceptives", "high_risk_pregnancy_inconsistent_contraceptives", "high_risk_pregnancy_unprotected_sex", "high_risk_pregnancy_infertility_treatment", "high_risk_pregnancy_postpartum", "high_risk_pregnancy_none", "high_risk_fem_noinfo", "high_risk_fem_unknown", "high_risk_fem_notasked", "high_risk_fem_askunknown", "high_risk_fem_invalid", "high_risk_fem_na", "pregnancy_test_and_contraceptive_agreement", "low_risk_pregnancy_effective_contraceptives", "menopause", "low_risk_pregnancy_surgical_sterilization", "low_risk_pregnancy_no_sex_6_months", "low_risk_pregnancy_no_sex", "low_risk_pregnancy_infertility_diagnosis", "low_risk_pregnancy_exclusive_homo_sexual_behavior", "low_risk_fem_noinfo", "low_risk_fem_unknown", "low_risk_fem_notasked", "low_risk_fem_askunknown", "low_risk_fem_invalid", "low_risk_fem_na", "contraceptive_continuation_agreement", "lab_notes", "consultation_schedule_date", "eleg_lab_request_date", "lab_schedule_date", "eleg_lab_location", "lab_collected_yn", "lab_checked_yn", "lab_finding_yn", "lab_exclusion_yn", "bhcg", "contraception", "preserved_hormone", "contraception_ready_yn", "contraception_ineligibility", "consent_sent_yn", "consent_read_yn", "consent_questions_yn", "consent_questions_2_yn", "consent_questions_cleared_yn", "participant_desire_yn", "first_visit_date", "sms_consent_yn", "block_alerts_1st_yn", "interview_datetime", "eleg_interviewer", "eleg_complete"),
    tcle = c("consent_signed_yn", "consent_date", "consent_upload", "tcle_complete"),
    demographic = c("race", "race_other", "marital_status", "education_years", "employment_status", "household_size", "income_level", "demographic_metadata", "demographic_complete"),
    whoqol = c("whoqol_timestamp", "whoqol_1_quality", "whoqol_2_health", "whoqol_3_pain", "whoqol_4_treatment", "whoqol_5_enjoyment", "whoqol_6_meaning", "whoqol_7_concentration", "whoqol_8_security", "whoqol_9_environment", "whoqol_10_energy", "whoqol_11_appearance", "whoqol_12_finances", "whoqol_13_information", "whoqol_14_leisure", "whoqol_15_mobility", "whoqol_16_sleep", "whoqol_17_activities", "whoqol_18_work", "whoqol_19_selfesteem", "whoqol_20_relationships", "whoqol_21_sexual", "whoqol_22_support", "whoqol_23_housing", "whoqol_24_health_services", "whoqol_25_transport", "whoqol_26_negativity", "whoqol_needed_help", "whoqol_comment", "whoqol_score_overall", "whoqol_score_health", "whoqol_score_physical", "whoqol_score_psychological", "whoqol_score_social", "whoqol_score_environment", "pdf_upload_wb", "whoqol_complete"),
    dass = c("dass_timestamp", "dass_1_not_calm", "dass_2_drymouth", "dass_3_not_positive", "dass_4_hard_breath", "dass_5_no_initiative", "dass_6_exaggeration", "dass_7_tremor", "dass_8_nervous", "dass_9_worry", "dass_10_no_desire", "dass_11_agitation", "dass_12_not_relaxed", "dass_13_depression", "dass_14_intolerance", "dass_15_panic", "dass_16_no_enthusiasm", "dass_17_no_selfworth", "dass_18_too_emotional", "dass_19_palpitation", "dass_20_fear", "dass_21_no_meaning", "dass_score_depression", "dass_score_anxiety", "dass_score_stress", "dass21_upload", "dass_complete"),
    ecap = c("ecap_timestamp", "ecap1", "ecap2", "ecap3", "ecap4", "ecap5", "ecap6", "ecap7", "ecap8", "ecap9", "ecap10", "ecap11", "ecap12", "ecap13", "ecap14", "ecap15", "ecap16", "ecap_response_date", "ecap_1_body_image", "ecap_2_eating_speed", "ecap_3_impulse", "ecap_4_emotional_eating", "ecap_5_hunger", "ecap_6_guilt", "ecap_7_diet_failure", "ecap_8_binge_quantity", "ecap_9_compensate", "ecap_10_control", "ecap_11_fullness", "ecap_12_social_eating", "ecap_13_meal_frequency", "ecap_14_worry", "ecap_15_food_thoughts", "ecap_16_hunger_awareness", "ecap_score", "ecap_pdf_upload", "ecap_complete"),
    bodycount = c("height", "height_checked_cm", "weight", "weight_checked_kg", "abdomen", "abdominal_circ_checked_cm", "arm", "arm_circ_checked_cm", "anthro_check_error", "anthro_check", "bmi", "weight_maxideal", "weight_adjusted", "kcal_kg20", "kcal_kg22", "diet_energy", "weight_loss_kg", "weight_loss_percent", "abdomen_loss_kg", "abdomen_loss_percent", "bmi_loss_absolute", "bmi_loss_percent", "bodycount_complete"),
    bp_limb = c("bpbia_form_open_date", "bpbia_examiner", "bpbia_r_sw", "cuff_size", "reference_systolic_right", "reference_diastolic_right", "reference_mean_right", "reference_systolic_left", "reference_diastolic_left", "reference_mean_left", "reference_member", "bp_limb_complete"),
    bp = c("bp_form_open_date", "bp_examiner", "bp_start_sw", "heart_rate", "oxigen_saturation", "systolic_1", "diastolic_1", "bp_mean_1", "bp_first_measurement_sw", "systolic_2", "bp_r21s_checked", "diastolic_2", "bp_r22d_checked", "bp_mean_2", "bp_second_measurement_sw", "systolic_3", "bp_r31s_checked", "diastolic_3", "bp_r32d_checked", "bp_mean_3", "bp_sys_diff", "bp_third_measurement_sw", "systolic_4", "bp_r41s_checked", "diastolic_4", "bp_r42d_checked", "bp_mean_4", "systolic_mean", "systolic_stdev", "diastolic_mean", "diastolic_stdev", "mean_bp_mean", "mean_bp_stdev", "bp_show_metadata", "bp_complete"),
    bia = c("bia_raw_files", "bia_form_open_date", "bia_examiner", "smoked_24h", "exercised_24h", "alcohol_24h", "room_temperature", "axillary_temperature", "light_clothes", "removed_objects", "hairy_limbs", "removed_hair", "cleaned_skin", "last_meal_time", "last_liquid_time", "bed_rest_10min", "bia_timestamp", "time_fasted_food", "time_fasted_liquid", "resistance", "resistance_checked", "reactance", "reactance_checked", "phase_angle", "phase_angle_checked", "bia_show_metadata", "bia_complete"),
    handgrip = c("grip_limitations_yn", "grip_rh_limitations", "grip_lh_no_limitations", "grip_lh_paralysis", "grip_lh_cast", "grip_lh_bandaged", "grip_lh_missing_thumb", "grip_lh_other_limitations", "grip_lh_no_info", "grip_lh_unknown", "grip_lh_notasked", "grip_lh_askunknown", "grip_lh_invalid", "grip_lh_na", "grip_recent_surgery_yn", "grip_exclude_test_yn", "grip_surgery_history_yn", "grip_dominance", "grip_pain_last7days_yn", "grip_rhpain", "grip_lhpain", "grip_test_procedure_understanding_yn", "handgrip_right_1", "grip_rh_validation1", "grip_rh_stopwatch1", "handgrip_left_1", "grip_lh_validation1", "grip_lh_stopwatch1", "handgrip_right_2", "grip_rh_validation2", "grip_rh_stopwatch2", "handgrip_left_2", "grip_lh_validation2", "grip_lh_stopwatch2", "handgrip_right_3", "grip_rh_validation3", "handgrip_left_3", "grip_lh_validation3", "handgrip_right_mean", "handgrip_right_stdev", "handgrip_left_mean", "handgrip_left_stdev", "grip_see_metadata", "handgrip_complete"),
    nutrition = c("frequency_bowel", "frequency_solid_stool", "frequency_diarrhea", "contipation_yn", "frequency_laxative", "urinary_frequency", "water_consumption", "hair_loss", "nutrition_complete"),
    food_allergy = c("food_alergy", "peanut_allergy", "nut_allergy", "seafood_allergy", "egg_allergy", "lactose_intolerance", "gluten_intolerance", "soy_allergy", "fish_allergy", "allergy_complete"),
    evs = c("evs_days", "evs_time", "evs_score", "exercise_type_1", "secondary_physical_activity_yn", "tertiary_physical_activity_yn", "evs_complete"),
    alcohol = c("alcohol_frequency", "alcohol_stopped_years_ago", "years_drinks_alcohol", "beer_yn", "wine_yn", "spirit_yn", "alcohol_type_other", "alcohol_type_no_info", "alcohol_type_unknown", "alcohol_type_not_asked", "alcohol_type_asked_unknown", "alcohol_type_invalid", "alcohol_type_na", "beer_per_week", "beer_dose", "wine_ml_per_week", "wine_dose", "distilled_ml_per_week", "spirit_dose", "alcohol_type_other_specify", "alcohol_other_doses_per_week", "alcohol_dose", "alcohol_significant", "alcohol_complete"),
    tobacco = c("smoke_history", "age_started_smoking", "smoked_years", "daily_cigarettes", "pack_years", "age_quit_smoking", "tobacco_complete"),
    diet_recall = c("time_1", "time_2", "time_3", "time_4", "time_5", "time_6", "food_1", "food_2", "food_3", "food_4", "food_5", "food_6", "observations_1", "observations_2", "observations_4", "observations_3", "observations_5", "observations_6", "pdf_upload_recordatorio", "diet_recall_complete", "meal_breakfast_yn", "meal_morning_snack_yn", "meal_lunch_yn", "meal_afternoon_snack_yn", "meal_dinner_yn", "meal_supper_yn", "meal_no_info", "meal_unknown", "meal_not_asked", "meal_asked_unknown", "meal_invalid", "meal_na"),
    diet_values = c("total_energy", "carbs_grams", "carbs_kcal", "protein_kcal", "fat_kcal", "protein_grams", "fat_grams", "carbs_morning_g", "protein_morning_g", "fat_morning_g", "fat_morning_snack_g", "carbs_morning_snack_g", "protein_morning_snack_g", "carbs_lunch_g", "fat_lunch_g", "protein_lunch_g", "carbs_afternoon_snack_g", "fat_afternoon_snack_g", "protein_afternoon_snack_g", "fat_dinner_g", "protein_dinner_g", "carbs_dinner_g", "carbs_night_snack_g", "fat_night_snack_g", "protein_night_snack_g", "carbs_cal_morning", "protein_cal_morning", "fat_cal_morning", "total_cal_morning", "carbs_cal_morning_snack", "fat_cal_morning_snack", "protein_cal_morning_snack", "total_cal_morning_snack", "total_cal_lunch", "carbs_cal_lunch", "fat_cal_lunch", "protein_cal_lunch", "carbs_cal_afternoon_snack", "fat_cal_afternoon_snack", "protein_cal_afternoon_snack", "total_cal_afternoon_snack", "carbs_cal_dinner", "protein_cal_dinner", "fat_cal_dinner", "total_cal_dinner", "carbs_cal_night_snack", "protein_cal_night_snack", "fat_cal_night_snack", "total_cal_night_snack", "nutr_pdf_upload", "diet_values_complete"),
    dates = c("intervention_capsule_start_yn", "visit1_schedule_date", "weekly_alert_remove_yn", "intervention_start_date", "date_45d_complete", "visit2_schedule_date", "date_90d_complete", "visit3_schedule_date", "important_dates_link_hidden", "dates_complete"),
    allocation = c("participant_id", "allocation_group", "allocation_complete"),
    conditions = c("comorbidity_yn", "comorbidity_additional", "common_comorbidities", "comorbidities_diagnosis_duration", "comorbidities_diagnosis_duration_unit", "comorbidities_listed_concat", "comorbidities_metadata", "conditions_complete"),
    drugs = c("medication_current_yn", "medication_additional", "common_medications", "medication_dosage", "drug_duration_use", "drug_duration_use_unit", "drug_units_per_dose", "drug_dosage_units", "medication_list_concat", "other_medication_use_yn", "medications_metadata", "drugs_complete"),
    old_drugs = c("previous_medication_yn", "previous_medication_additional", "common_previous_medications", "previous_drug_start_info", "previous_drug_start_duration", "previous_drug_start_duration_unit", "previous_drug_stop_info", "previous_drug_stop_duration", "previous_drug_stop_duration_unit", "previous_medications_listed_concat", "other_medications", "old.drugs_complete"),
    old_conditions = c("medical_history_yn", "medical_history_additional", "common_medical_history", "personal_medical_history", "personal_medical_history_notes", "medical_history_duration", "medical_history_duration_unit", "medical_history_listed_concat", "old.conditions_complete"),
    symptoms = c("symptoms_yn", "symptoms_additional", "symptom_instance_number", "symptom_code", "symptom_specify", "symptom_note", "symptom_onset", "symptom_onset_code", "symptom_onset_unit", "symptom_severity", "symptom_severity_scale", "symptom_current", "symptom_current_or_resolved", "symptom_resolution_date", "symptom_resolution_duration_unit", "symptom_causality_assessment", "symptom_intervention_causality", "symptoms_concat", "symptoms_complete"),
    phy_exam = c("physical_exam_findings_yn", "physical_exam_findings_additional", "system", "general_appearance", "oral_cavity_exam", "skin_exam", "cardiovascular_exam", "respiratory_exam", "abdominal_exam", "extremities_exam", "abnormal_finding_description", "abnormal_finding_nonindexed_description", "previous_instance_phyexam_concat", "current_instance_phyexam_concat2", "phy.exam_complete"),
    labs = c("show_lab_list_yn", "lab_request_signed_pdf", "lab_protocol_request_pdf", "medical_consultation_schedule_date", "lab_request_date", "lab_scheduled_date", "lab_location", "labs_date", "c_reactive_protein", "ast", "alt", "gamma_gt", "alkaline_phosphatase", "total_bilirubin", "direct_bilirubin", "indirect_bilirubin", "amylase", "total_proteins", "albumin", "urea", "creatinine", "glomerular_filtration_rate", "cpk", "uric_acid", "sodium", "potassium", "calcium_ionic", "total_cholesterol", "ldl", "hba1c", "triglycerides", "hdl", "fasting_glucose", "insulin", "homa_ir", "quick_index", "beta_hcg", "hemoglobin", "hematocrit", "leukocytes", "platelets", "tsh", "t4_free", "lab_exam_pdf", "other_lab_tests_yn", "labs_notes", "labs_checked_results", "lab_metadata", "labs_complete"),
    ecg = c("ecg_timestamp", "ecg_performed", "reason_not_performed_ecg", "ecg_pdf_upload", "amplitude_standard", "heart_rate_bpm", "sample_time_s", "qrs_interval_ms", "pr_interval_ms", "qt_interval_ms", "qtc_interval_ms", "qrs_axis_degrees", "rhythm", "normal_ecg", "ecg_findings_lbbb", "ecg_findings_rbbb", "ecg_findings_av_block", "ecg_findings_st_changes", "ecg_findings_abnormal_q_waves", "ecg_findings_nonspecific_intraventricular_conduction_delay", "ecg_findings_no_info", "ecg_findings_unknown", "ecg_findings_not_asked", "ecg_findings_asked_but_unknown", "ecg_findings_invalid", "ecg_findings_na", "ecg_text_prompt", "ecg_audit_data", "ecg_technical_quality", "ecg_measurement_checked", "show_ecg_metadata_yn", "ecg"),
    compliance = c("taking_as_directed", "dosage_schedule", "alternative_schedule", "reminder_method", "alternative_reminder", "missed_study_medication", "missed_dose_count", "missed_dose_timing", "missed_dose_timing_other", "medication_discontinuation", "discontinuation_duration", "discontinuation_reason", "discontinuation_reason_other", "ran_out_of_medication", "ran_out_reason", "daily_routine_change_medication_adherence_yn", "daily_routine_change_specify", "perceived_improvement", "improvements_reported", "challenges_taking_medication", "specify_challenges_medication_adherence", "medication_confidence_scale", "overall_compliance_rate", "compliance_complete"),
    adverse_event = c("adverse_event_evaluation_date", "adverse_event_this_cycle_yn", "serious_adverse_event_yn", "adverse_event", "adverse_event_description", "adverse_event_classification", "adverse_event_grade", "adverse_event_start_date", "adverse_event_end_date", "adverse_event_attribution", "adverse_event_action_taken", "adverse_event_followup", "additional_adverse_events_yn", "adverse_event_concat", "adverse_complete"),
    medical = c("evaluation_date", "pipe_comorbidities", "diuretic_use", "diuretic_dose_change", "pipe_current_medications", "pipe_previous_medications", "pipe_medical_history", "menses", "regular_cycle", "cycle_duration", "last_menses", "ovulation_days_after_lmp", "next_ovulation_date", "next_menses_date", "cycle_phase", "drugs_dose_change", "drugs_dose_change_notes", "pipe_symptoms_1st_visit", "pipe_symptoms_2nd_visit", "pipe_symptoms_3rd_visit", "phy_exam_1st_concat", "phy_exam_2nd_concat", "phy_exam_3rd_concat", "show_lab_yn", "lab_tests_yn", "lab_tests_not_performed_reason", "lab_tests_checked_yn", "abnormal_labs", "abnormal_labs_conduct", "intervention_prevention_reason_yn", "specify_intervention_prevention_reasons", "intervention_delivered_yn", "explain_intervention_not_delivered", "date_delivery", "explained_dosage", "intervention_comprehension_yn", "intervention_comprehension_notes", "expected_start_date", "expected_start_date_capsules", "start_after_lab", "additional_notes_actions_yn", "medical_conduct", "medical_complete"),
    followup = c("weekly_followup_timestamp", "is_data_entry_form_yn", "interviewer_followup", "first_contact_attempt_datetime", "first_contact_successful_yn", "second_contact_attempt_datetime", "second_contact_successful_yn", "third_contact_attempt_datetime", "third_contact_successful_yn", "fourth_contact_attempt_datetime", "fourth_contact_successful_yn", "fifth_contact_attempt_datetime", "fifth_contact_successful_yn", "sixth_contact_attempt_datetime", "sixth_contact_successful_yn", "seventh_contact_attempt_datetime", "seventh_contact_successful_yn", "eighth_contact_attempt_datetime", "eighth_contact_successful_yn", "ninth_contact_attempt_datetime", "ninth_contact_successful_yn", "tenth_contact_attempt_datetime", "tenth_contact_successful_yn", "symptoms_since_treatment", "symptoms_description", "contact_info_start_days", "onset_days", "contact_info_severity", "severity_scale", "symptoms_resolved", "contact_info_duration_days", "resolved_days", "capsules_compliance", "missed_dose_last_week", "reason_not_compliant", "questions_yn", "question_notes", "questions_resolved_yn", "pdf_survey_upload", "followup_complete"),
    conclusion = c("completed_intervention", "conclusion_date", "non_completion_reason", "conclusion_info_view_yn", "ethical_additional_measures_details", "ethical_additional_measures_yn", "ethical_additional_measures_info", "conclusion_complete"),
    annex = c("attachment_insertion_date", "attachment_type", "attachment_file_date", "attachment_other_specify", "attachment_file_upload", "attachment_notes", "attachment_complete_yn")
)

writeLines(
    capture.output(
        print(instruments)
    ), 
    "/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/PROJECTS/DVEP/3_Output/4_Instruments.txt")

# Selecting variables that are relevant for the analysis
# Filter the codebook to include only the variables where "included" == 1
selected_variables <- codebook |> 
    filter(included == 1)  |> 
    pull(variable_recoded)  # Extract the variable names into a vector

# Use the select function to select only the variables of interest from the dataset
data_filtered <- data  |> 
    select(all_of(selected_variables))  # all_of ensures compatibility with character vectors