---
title: "Descriptive statistics"
project: "Effect of Eclipta prostrata (L.) L. (Asteraceae) on bioelectrical impedance phase angle in adults with grade I obesity"
PID: "1958"
author: "Moura, G.S.P.L"
date: "2024-10-22"
output: html_document
---
# $redcap
[1] "event_name"        "repeat_instrument" "repeat_instance"  

# $elegibility
 [1] "record_id"                                         "date_birth"                                       
 [3] **"age"**                                           "ubs"                                              
 [5] "contact_options"                                   "contact_hours"                                    
 [7] "contact_days"                                      "transport_research_center"                        
 [9] "research_source_info"                              "availability_comments_yn"                         
[11] "availability_comments"                             **"sex"**                                              
[13] "pregnant_nursing_yn"                               "relatada"                                         
[15] "eleg_weight"                                       "bmi_reported"                                     
[17] **"eleg_comorbidity_yn"**                           "comorbidity_list"                                 
[19] **"drug_use_yn"**                                       "drug_list"                                        
[21] "high_risk_pregnancy_ineffective_contraceptives"    "high_risk_pregnancy_inconsistent_contraceptives"  
[23] "high_risk_pregnancy_unprotected_sex"               "high_risk_pregnancy_infertility_treatment"        
[25] "high_risk_pregnancy_postpartum"                    "high_risk_pregnancy_none"                         
[27] "high_risk_fem_noinfo"                              "high_risk_fem_unknown"                            
[29] "high_risk_fem_notasked"                            "high_risk_fem_askunknown"                         
[31] "high_risk_fem_invalid"                             "high_risk_fem_na"                                 
[33] "pregnancy_test_and_contraceptive_agreement"        "low_risk_pregnancy_effective_contraceptives"      
[35] "menopause"                                         "low_risk_pregnancy_surgical_sterilization"        
[37] "low_risk_pregnancy_no_sex_6_months"                "low_risk_pregnancy_no_sex"                        
[39] "low_risk_pregnancy_infertility_diagnosis"          "low_risk_pregnancy_exclusive_homo_sexual_behavior"
[41] "low_risk_fem_noinfo"                               "low_risk_fem_unknown"                             
[43] "low_risk_fem_notasked"                             "low_risk_fem_askunknown"                          
[45] "low_risk_fem_invalid"                              "low_risk_fem_na"                                  
[47] "contraceptive_continuation_agreement"              "lab_notes"                                        
[49] "consultation_schedule_date"                        "eleg_lab_request_date"                            
[51] "lab_schedule_date"                                 "eleg_lab_location"                                
[53] "lab_collected_yn"                                  "lab_checked_yn"                                   
[55] "lab_finding_yn"                                    "lab_exclusion_yn"                                 
[57] "bhcg"                                              "contraception"                                    
[59] "preserved_hormone"                                 "contraception_ready_yn"                           
[61] "contraception_ineligibility"                       "consent_sent_yn"                                  
[63] "consent_read_yn"                                   "consent_questions_yn"                             
[65] "consent_questions_2_yn"                            "consent_questions_cleared_yn"                     
[67] "participant_desire_yn"                             "first_visit_date"                                 
[69] "sms_consent_yn"                                    "block_alerts_1st_yn"                              
[71] "interview_datetime"                                "eleg_interviewer"                                 
[73] "eleg_complete"                                    

```{r, echo=FALSE}
print(paste("Number of participants:", sum(!is.na(data$age))))
summary(data$age)
summary(data$eleg_comorbidity_yn.factor) # participantes com comorbidades
summary(data$drug_use_yn.factor) # Faz uso de medicamentos contínuos
```



```{r}
# Convert 'consent_date' from character to Date
data$consent_date <- as.Date(data$consent_date, format = "%Y-%m-%d")  # Adjust the format if necessary
summary(data$consent_date)
```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```