# Bioelectrical impedance analysis (BIA) data analysis

## Data Source
    Before the beginning of the study, a dedicated profile was created on the device used to perform the BIA (SECA) on study participants. This specific profile, protected with password, was used during the study. The devide is equiped with an internal memory system that stores all results on each participant's own folder.
    In order to avoid data loss, at the end of a day of participant evaluation, every exam perfomed on that data was exported to a Sandisk pendrive directly from the device  - one file per patient. The results were then transfered to the main researcher's personal computer, and stored on a specific folder, which was also synked to ICloud. Therefore, 4 copies of each file were continuously maintained.

## Data Import
    The BIA device exports the exam results as and XML file. The structure of the XML file is detailed below. Let us note that each time a tab space is inserted in reference to the line above it, this indicated that the subsequent lines indicate child nodes, nested within the parent row. The file structure is as follows. 

**XML File structure**

## Data parsing and wrangling 
    All XML files were parsed with OpenRefine into a single csv file. subsequently, using M code in Microsoft Power Query, the csv file was transformed into the final data spreadsheet.

    The following M code was used for data transformation:

```bash
let
    Source = Csv.Document(File.Contents("/Users/gustavosplmoura/Library/Mobile Documents/com~apple~CloudDocs/Medicina/Biblioteca/Research/Data Science/Data Science/DVEP/BIA_xml/xml_to_csv/241002.txt"), [Delimiter = ",", Columns = 64, QuoteStyle = QuoteStyle.None]),
    #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),

    #"Renamed Columns" = Table.RenameColumns(#"Promoted headers", List.Transform(Table.ColumnNames(#"Promoted headers"), each {_, Text.AfterDelimiter(_, " - ", {0, RelativePosition.FromEnd})})),

    #"Changed column type" = Table.TransformColumnTypes(#"Renamed Columns", {{"File", type text}, {"State", type text}, {"Frequency", Int64.Type}, {"LbhReal", type number}, {"LbhImaginary", type number}, {"RbhReal", type number}, {"RbhImaginary", type number}, {"LahReal", type number}, {"LahImaginary", type number}, {"LlhReal", type number}, {"LlhImaginary", type number}, {"RahReal", type number}, {"RahImaginary", type number}, {"RlhReal", type number}, {"RlhImaginary", type number}, {"TohReal", type number}, {"TohImaginary", type number}, {"MeasurementGUID", type text}, {"TimeStamp", type datetime}, {"MeasuringDevice", Int64.Type}, {"ExportToCSV", Int64.Type}, {"ExportToKIS", Int64.Type}, {"CommentTimeStamp", type datetime}, {"Weight", type number}, {"Height", type number}, {"Waist", type number}, {"Pal", type number}, {"Bmi", type number}, {"TotalEnergyExpediture", type number}, {"RestingEnergyExpediture", type number}, {"EnergyStored", type number}, {"RAverage", type number}, {"XcAverage", type number}, {"FmAbsolute", type number}, {"Fmi", type number}, {"FmRelative", type number}, {"FfmAbsolute", type number}, {"Ffmi", type number}, {"FfmRelative", type number}, {"Body", type number}, {"Torso", type number}, {"RightArm", type number}, {"LeftArm", type number}, {"RightLeg", type number}, {"LeftLeg", type number}, {"Vat", type number}, {"PhaseAngle", type number}, {"Tbw", type number}, {"Ecw", type number}, {"TbwRelative", type number}, {"EcwRelative", type number}, {"EcwBytbw", type number}, {"DeviceId", type text}, {"MatSerial", Int64.Type}, {"GUID", type text}, {"ID", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"DateOfBirth", type datetime}, {"Gender", type text}, {"Ethnic", type text}, {"Doctor", type text}, {"LastModified", type datetime}, {"IsDeleted", Int64.Type}}),

    #"Sorted Rows" = Table.Sort(#"Changed column type", {{"File", Order.Ascending}, {"TimeStamp", Order.Ascending}}),

    #"Replaced Empty with Null" = Table.ReplaceValue(#"Sorted Rows", "", null, Replacer.ReplaceValue, {"DateOfBirth", "Gender", "Ethnic", "FirstName", "LastName"}),

    #"Filled Down" = Table.FillDown(#"Replaced Empty with Null", {"ID", "DateOfBirth", "Gender", "Ethnic", "FirstName", "LastName"}),

    #"Added Date Column" = Table.AddColumn(#"Filled Down", "Date", each DateTime.Date([TimeStamp]), type date),
    #"Added Time Column" = Table.AddColumn(#"Added Date Column", "Time", each DateTime.Time([TimeStamp]), type time),

    #"Removed Unnecessary Columns" = Table.RemoveColumns(#"Added Time Column", {"State", "Frequency", "LbhReal", "LbhImaginary", "RbhReal", "RbhImaginary", "LahReal", "LahImaginary", "LlhReal", "LlhImaginary", "RahReal", "RahImaginary", "RlhReal", "RlhImaginary", "TohReal", "TohImaginary", "MeasurementGUID", "MeasuringDevice",	"ExportToCSV",	"ExportToKIS",	"CommentTimeStamp","DeviceId",	"MatSerial",	"GUID", "Doctor",	"LastModified",	"IsDeleted"}),

    #"Reordered Columns" = Table.ReorderColumns(#"Removed Unnecessary Columns", {"ID", "Date", "Time", "DateOfBirth", "Gender", "Ethnic", "Weight", "Height", "Bmi", "Waist", "PhaseAngle", "RAverage", "XcAverage", "FmAbsolute", "Fmi", "FmRelative", "FfmAbsolute", "Ffmi", "FfmRelative", "Body", "Torso", "RightArm", "LeftArm", "RightLeg", "LeftLeg", "Vat", "Tbw", "Ecw", "TbwRelative", "EcwRelative", "EcwBytbw", "Pal", "TotalEnergyExpediture", "RestingEnergyExpediture", "EnergyStored", "TimeStamp", "File", "FirstName", "LastName"}),

    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each ([PhaseAngle] <> null))
in
    #"Filtered Rows"
```
    As can be seen from the M code, the process of data transformation performed within Microsoft Power Query involved:

    1. Renaming the variable names represented as the first row of data by extracting the last XML node of the original names;
    2. Applying the appropriate transformations of column data type for each variable, such as text, number, of datetime, ensuring excel would accurately represent the data. 
    3. Sorting the spreadsheet by the values of "File" and "TimeStamp" columns, both from smallest to largest. In this way, the results for each participant were grouped and sorted based on the date of the BIA evaluation.
    4. Adding "null" to blank cells
    5. Fill down blank rows with patient data, since, in the original XML file, the nodes containing patient data were not repeated on each patient measurement.
    6. Splitting the "Timestamp" column into two columns: "Date" and "Time"
    7. Removing unwanted columns. Particularly, two main types of columns were not included in the file data spreadsheet. The first corresponds to a group of subsequent columns storing results for values not directly applicable to this clinical study, related to measurements of diverse frequencies.
    8. Reordering of columns such that the data presentation would follow a more logical sequence, facilitating data analysis.
    9. The last step in the M code corresponds to filtering out of the rows that contained participant data but did not contain any measured BIA parameters. This was accomplished by filtering out rows where "PhaseAngle" were null.

## Adding exam index 
    After applying the M code, the power query editor was closed and the spreadsheet loaded. As a final step before the conducting of exploratory data analysis, two additional columns were created, as follows:

    1. Column C, labelled as "visit", was created in order to add an index of integers, where the integer count would increase for each patient when the date value changed, suggesting the exams were performed on different dates, and resetting back to "1" for a patient's first record. 
    2. Column D, labeled as "datedif", allowed to create a precise day count between the first measurement date and the subsequent exams performed. In this way, the first measurement date is the reference for which all date differences are calculated. 

    The formulas for C2 and D2 are respectively reported below:
    =IF(AND(A2=A1,B2=B1),C1,IF(AND(A2=A1,B2<>B1),C1+1,1))
    =IF(C2=1,1,IF(AND(C2=2,C1=1),B2-B1,IF(AND(C2=2,C1=2),D1,IF(AND(C2=3,OFFSET(C2,-1,0)=2,OFFSET(C2,-2,0)=1),B2-OFFSET(B2,-2,0),""))))