#Clear existing data and graphics
rm(list=ls())
graphics.off()
#Load  necessary libraries
library(Hmisc)
library(dplyr)
#Read Data
data=read.csv('EffectOfEcliptaProst_DATA_2024-10-20_1615.csv')
#Setting Labels

label(data$record_id)="Nome completo"
label(data$redcap_event_name)="Event Name"
label(data$redcap_repeat_instrument)="Repeat Instrument"
label(data$redcap_repeat_instance)="Repeat Instance"
label(data$redcap_survey_identifier)="Survey Identifier"
label(data$personal_photo)="Foto pessoal identificadora [personal_photo:inline]"
label(data$date_birth)="Data de nascimento"
label(data$eleg_age)="Idade"
label(data$ubs)="UBS/ESF "
label(data$email)="Email:"
label(data$address)="Endereço"
label(data$hood)="Bairro"
label(data$mobile)="Validação: +55 seguido do DDD (2 dígitos) e número de celular (9 dígitos), sem espaços Chat on WhatsApp orCall"
label(data$whatsapp)="WhatsApp link or phone call link"
label(data$mob_option)="Quais as formas possíveis de contato pelo celular?"
label(data$mob_hour)="Quais os horários possíveis para contato?"
label(data$mob_days)="Quais os dias possíveis para contato?"
label(data$phone)="Número de telefone fixo:"
label(data$otherphone)="Número do telefone alternativo:"
label(data$otherphone_n)="Nome do contato do telefone alternativo"
label(data$otherphone_2)="Número do telefone alternativo:"
label(data$otherphone_n2)="Nome do contato do telefone alternativo"
label(data$eleg_transport)="Transporte ao centro de pesquisa"
label(data$eleg_howknow)="Forma como ficou sabendo da pesquisa"
label(data$availability_limit_yn)="Comentários ou limitações sobre a disponibilidade de dias / horários para comparecer ao centro de pesquisa"
label(data$availability_limit)="Comentários ou limitações sobre a disponibilidade de dias / horários para comparecer ao centro de pesquisa"
label(data$sex)="Sexo"
label(data$eleg_preg_yn)="A candidata está grávida ou amamentando?"
label(data$eleg_height)="Altura (cm), relatada"
label(data$eleg_weight)="Peso (kg), relatado:ponto como separador decimal, 1 casa decimal"
label(data$eleg_bmi)="IMC (relatado)"
label(data$eleg_com_yn)="O candidato relata ter qualquer outro problema de saúde além da obesidade?"
label(data$eleg_com_list)="Quais? "
label(data$eleg_drugs_yn)="O candidato faz uso de algummedicamento?"
label(data$eleg_drugs_list)="Quais? (liste todos)"
label(data$eleg_fem_high___1)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Utilização de contraceptivos ineficazes, que incluem uso exclusivo de: método de barreia (preservativo, diafragma) ou métodos comportamentais, como temperatura corporal, percepção da ovulação pelo corrimento e calendário menstrual (tabelinha))"
label(data$eleg_fem_high___2)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Mulheres que usam contraceptivos de forma inconsistente ou incorreta;)"
label(data$eleg_fem_high___3)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Mulheres que tiveram relações sexuais sem proteção;)"
label(data$eleg_fem_high___4)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Mulheres que estão em tratamento para infertilidade;)"
label(data$eleg_fem_high___5)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Mulheres no período pós-parto;)"
label(data$eleg_fem_high___0)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Nenhum destes)"
label(data$eleg_fem_high___ni)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=No information)"
label(data$eleg_fem_high___unk)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Unknown)"
label(data$eleg_fem_high___nask)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Not asked)"
label(data$eleg_fem_high___asku)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Asked but unknown)"
label(data$eleg_fem_high___inv)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Invalid)"
label(data$eleg_fem_high___na)="A candidata apresenta algum dos critérios de alto risco de gravidez? (choice=Not applicable)"
label(data$eleg_femhigh_yn)="Nestes casos, a realização de teste de gravidez é obrigatória, assim como a utilização de método contraceptivo eficaz durante o estudo. A escolha do método contraceptivo dependerá de decisão conjunta entre participante e médico. A participante concorda em realizar teste de gravidez Eutilizar método contraceptivo durante o estudo?"
label(data$eleg_fem_low___1)="Marque todos os itens que se aplicam a candidata (choice=Uso de contraceptivos eficazes de forma consistente e correta. São considerados métodos eficazes: contraceptivos hormonais como pílulas, adesivos, injetáveis, anéis, implantes subdérmicos ou dispositivos intrauterinos)"
label(data$eleg_fem_low___2)="Marque todos os itens que se aplicam a candidata (choice=Mulheres que estão em menopausa)"
label(data$eleg_fem_low___3)="Marque todos os itens que se aplicam a candidata (choice=Mulheres submetidas a cirurgias que impossibilitam a gestação: esterilização cirúrgica (ligadura tubária ou vasectomia do parceiro), ooforectomia bilateral (retirada dos 2 ovários) ou histerectomia (retirada do útero).)"
label(data$eleg_fem_low___4)="Marque todos os itens que se aplicam a candidata (choice=Ausência de relações sexuais nos últimos 6 meses ou mais)"
label(data$eleg_fem_low___5)="Marque todos os itens que se aplicam a candidata (choice=Não tem qualquer tipo de relação sexual)"
label(data$eleg_fem_low___6)="Marque todos os itens que se aplicam a candidata (choice=Diagnóstico de infertilidade)"
label(data$eleg_fem_low___7)="Marque todos os itens que se aplicam a candidata (choice=Comportamento sexual homoafetivo exclusivo)"
label(data$eleg_fem_low___ni)="Marque todos os itens que se aplicam a candidata (choice=No information)"
label(data$eleg_fem_low___unk)="Marque todos os itens que se aplicam a candidata (choice=Unknown)"
label(data$eleg_fem_low___nask)="Marque todos os itens que se aplicam a candidata (choice=Not asked)"
label(data$eleg_fem_low___asku)="Marque todos os itens que se aplicam a candidata (choice=Asked but unknown)"
label(data$eleg_fem_low___inv)="Marque todos os itens que se aplicam a candidata (choice=Invalid)"
label(data$eleg_fem_low___na)="Marque todos os itens que se aplicam a candidata (choice=Not applicable)"
label(data$eleg_fem_low_1)="Orientar a candidata que, nestes casos, a participante deverá manter o uso contínuo e regular do método contraceptivo durante o estudo. A participante concorda?"
label(data$eleg2_labnotes)="Comentários"
label(data$d_consulta_agendamento_2)="Data da consulta médica criada no RKM para agendamento dos exames laboratoriais"
label(data$eleg2_labrequest_2)="Data em que foi feita a solicitação dos exames laboratoriais:"
label(data$eleg2_labschedule_2)="Data agendada para coleta"
label(data$eleg2_whichlab_2)="Qual o local agendado para coleta?"
label(data$eleg2_labcollect)="Exames laboratoriais coletados?"
label(data$eleg2_labchecked)="Exames laboratoriais checados?"
label(data$eleg2_labfinding)="Alguma alteração nos exames laboratoriais?"
label(data$eleg2_labex)="Existe alguma alteração laboratorial excludente?"
label(data$eleg2_bhcg)="Beta HCG"
label(data$eleg2_f_highrisk_2)="Método contraceptivo:"
label(data$normalcycle)="O ciclo hormonal menstrual está preservado?"
label(data$contraception_ok)="Risco de gestação e método contraceptivo:A participante já pode iniciar o estudo?"
label(data$eleg2_contraception)="Atenção! Não incluir participante!"
label(data$tcle_sent)="TCLE enviado?"
label(data$tcle_read)="TCLE lido pelo participante?"
label(data$tcle_questions)="O participante tem alguma dúvida sobre os aspectos da pesquisa tratados no TCLE?"
label(data$tcle_questions_2)="TCLE dúvidas?"
label(data$tcle_questions_3)="Dúvidas esclarecidas?"
label(data$desire_ok_2)="O participante mantém desejo de participar?"
label(data$first_visit_2)="Data agendada para a primeira visita"
label(data$sms_agree)="Gostaria de *solicitar sua autorização* para te enviarmos algumas *mensagens de texto (SMS)*. Esta será uma das formas que iremos nos comunicar através durante a pesquisa. Se concordar, você irá receber mensagens de texto para te *lembrar de datas importantes como datas de consultas ou coleta de exames* ou para responder a alguns *questionários ou perguntas*que são importantes para a pesquisa. Você concorda?"
label(data$block_alerts_1st)="Block alerts for 1st visit and 1st questionnaires?"
label(data$eleg_date)="Data e hora da entrevista"
label(data$eleg_interviewer)="Entrevistador"
label(data$elegibilidade_complete)="Complete?"
label(data$consent_c16735_yn)="Primeira Visita ao centro de pesquisa Finalizar a obtenção do consentimento através da assinatura do TCLE. O TCLE foi assinado?"
label(data$consent_date)="Data da assinatura do TCLE"
label(data$consent_c16735)="Faça o upload do TCLE assinado e escaneado"
label(data$tcle_complete)="Complete?"
label(data$race)="Raça CDISC SDTM Race Terminology (NCIT: C74457)"
label(data$race_other)="Especifique"
label(data$maritalstatus)="Estado civilCDISC SDTM Marital Status Terminology (NCIT: C76348)"
label(data$education)="Número de anos que estudou Number of Years of Education (NCIT: C122393)"
label(data$employment)="Situação de emprego CDISC SDTM Employment Status Terminology (NCIT: C111108)"
label(data$cohabitants)="Número de pessoas que vivem na mesma casa Number of People in Household (NCIT: C198363)"
label(data$income)="Nível de renda Income level (NCIT: C154890)"
label(data$demographic_metadata)="Metadata (NCIT: C52095)All demographic and socioeconomic data is coded according to NCIT Ontology version 23.06d (2023-06-26)"
label(data$dados_demogrficos_complete)="Complete?"
label(data$questionrio_qualidade_de_vida_timestamp)="Survey Timestamp"
label(data$wb_1)="Como você avaliaria a sua qualidade de vida?"
label(data$wb_2)="Quão satisfeito(a) você está com a sua saúde?"
label(data$wb_3)="Em que medida você acha que sua dor (física) impede você de fazer o que você precisa?"
label(data$wb_4)="O quanto você precisa de algum tratamento médico para levar sua vida diária?"
label(data$wb_5)="O quanto você aproveita a vida?"
label(data$wb_6)="Em que medida você acha que a sua vida tem sentido?"
label(data$wb_7)="O quanto você consegue se concentrar?"
label(data$wb_8)="Quão seguro(a) você se sente em sua vida diária?"
label(data$wb_9)="Quão saudável é o seu ambiente físico (clima, barulho, poluição, atrativos)?"
label(data$wb_10)="Você tem energia suficiente para seu dia-a-dia?"
label(data$wb_11)="Você é capaz de aceitar sua aparência física?"
label(data$wb_12)="Você tem dinheiro suficiente para satisfazer suas necessidades?"
label(data$wb_13)="Quão disponíveis para você estão as informações que precisa no seu dia-a-dia?"
label(data$wb_14)="Em que medida você tem oportunidades de atividade de lazer?"
label(data$wb_15)="Quão bem você é capaz de se locomover?"
label(data$wb_16)="Quão satisfeito(a) você está com o seu sono?"
label(data$wb_17)="Quão satisfeito(a) você está com sua capacidade de desempenhar as atividades do seu dia-a-dia?"
label(data$wb_18)="Quão satisfeito(a) você está com sua capacidade para o trabalho?"
label(data$wb_19)="Quão satisfeito(a) você está consigo mesmo?"
label(data$wb_20)="Quão satisfeito(a) você está com suas relações pessoais (amigos, parentes, conhecidos, colegas)?"
label(data$wb_21)="Quão satisfeito(a) você está com sua vida sexual?"
label(data$wb_22)="Quão satisfeito(a) você está com o apoio que você recebe de seus amigos?"
label(data$wb_23)="Quão satisfeito(a) você está com as condições do local onde mora?"
label(data$wb_24)="Quão satisfeito(a) você está com o seu acesso aos serviços de saúde?"
label(data$wb_25)="Quão satisfeito(a) você está com o seu meio de transporte?"
label(data$wb_26)="Com que frequência você tem sentimentos negativos tais como mau humores, desespero, ansiedade, depressão?"
label(data$whoqol_how)="Alguém te ajudou a preencher este questionário?"
label(data$whoqol_a_v2)="Você tem algum comentário sobre o questionário?"
label(data$wb_1_score)="General quality of life: Score"
label(data$wb_2_score)="General health: Score	"
label(data$wb_physical)="Physical domain	"
label(data$wb_psychological)="Psychological domain	"
label(data$wb_social)="Social Relationships domain	"
label(data$wb_environment)="Environment domain	"
label(data$wb_upload)="PDF Upload"
label(data$questionrio_qualidade_de_vida_complete)="Complete?"
label(data$escore_de_depresso_ansiedade_e_estresse_timestamp)="Survey Timestamp"
label(data$dass21_1)="Achei difícil me acalmar"
label(data$dass21_2)="Senti minha boca seca"
label(data$dass21_3)="Não consegui vivenciar nenhum sentimento positivo"
label(data$dass21_4)="Tive dificuldade em respirar em alguns momentos (ex. respiração ofegante, falta de ar, sem ter feito nenhum esforço físico)"
label(data$dass21_5)="Achei difícil ter iniciativa para fazer as coisas"
label(data$dass21_6)="Tive a tendência de reagir de forma exagerada às situações"
label(data$dass21_7)="Senti tremores (ex. nas mãos)"
label(data$dass21_8)="Senti que estava sempre nervoso"
label(data$dass21_9)="Preocupei-me com situações em que eu pudesse entrar em pânico e parecesse ridículo (a)"
label(data$dass21_10)="Senti que não tinha nada a desejar"
label(data$dass21_11)="Senti-me agitado"
label(data$dass21_12)="Achei difícil relaxar"
label(data$dass21_13)="Senti-me depressivo (a) e sem ânimo"
label(data$dass21_14)="Fui intolerante com as coisas que me impediam de continuar o que eu estava fazendo"
label(data$dass21_15)="Senti que ia entrar em pânico"
label(data$dass21_16)="Não consegui me entusiasmar com nada"
label(data$dass21_17)="Senti que não tinha valor como pessoa"
label(data$dass21_18)="Senti que estava um pouco emotivo/sensível demais"
label(data$dass21_19)="Sabia que meu coração estava alterado mesmo não tendo feito nenhum esforço físico (ex. aumento da frequência cardíaca, disritmia cardíaca)"
label(data$dass21_20)="Senti medo sem motivo"
label(data$dass21_21)="Senti que a vida não tinha sentido"
label(data$dass_depression)="DASS-21 Depression Result"
label(data$dass_anxiety)="DASS-21 Anxiety Result	"
label(data$dass_stress)="DASS-21 Stress Result	"
label(data$dass21_upload)="PDF upload"
label(data$escore_de_depresso_ansiedade_e_estresse_complete)="Complete?"
label(data$escala_de_compulso_alimentar_timestamp)="Survey Timestamp"
label(data$ecap1)="#1"
label(data$ecap2)="#2"
label(data$ecap3)="#3"
label(data$ecap4)="#4"
label(data$ecap5)="#5"
label(data$ecap6)="#6"
label(data$ecap7)="#7"
label(data$ecap8)="#8"
label(data$ecap9)="#9"
label(data$ecap10)="#10"
label(data$ecap11)="#11"
label(data$ecap12)="#12"
label(data$ecap13)="#13"
label(data$ecap14)="#14"
label(data$ecap15)="#15"
label(data$ecap16)="#16"
label(data$data_ecap)="Data que o participante respondeu o questionário:"
label(data$ecap_score_1)="ECAP SCORE"
label(data$ecap_score_2)="ECAP SCORE"
label(data$ecap_score_3)="ECAP SCORE"
label(data$ecap_score_4)="ECAP SCORE"
label(data$ecap_score_5)="ECAP SCORE 5"
label(data$ecap_score_6)="ECAP SCORE 6"
label(data$ecap_score_7)="ECAP SCORE 7"
label(data$ecap_score_8)="ECAP SCORE 8"
label(data$ecap_score_9)="ECAP SCORE 9"
label(data$ecap_score_10)="ECAP SCORE 10"
label(data$ecap_score_11)="ECAP SCORE 11"
label(data$ecap_score_12)="ECAP SCORE 12"
label(data$ecap_score_13)="ECAP SCORE 13"
label(data$ecap_score_14)="ECAP SCORE 14"
label(data$ecap_score_15)="ECAP SCORE 15"
label(data$ecap_score_16)="ECAP SCORE 16"
label(data$ecap_result)="ECAP Result"
label(data$ecap_upload)="PDF upload"
label(data$escala_de_compulso_alimentar_complete)="Complete?"
label(data$height)="Altura aferida em estadiômetro, expressa em centimetros(utilizar ponto como separador decimal e uma casa decimal)"
label(data$height_chk)="Altura aferida em estadiômetro, expressa em centimetros(utilizar ponto como separador decimal e uma casa decimal)"
label(data$weight)="Peso aferido em balança calibrada, expresso em kilogramas:validação: uma casa decimal, ponto como separador decimal"
label(data$weight_chk)="Peso aferido em balança calibrada, expresso em kilogramas:validação: uma casa decimal, ponto como separador decimal"
label(data$abdcirc_c172954)="Circunferência abdominal, expressos em centímetosvalidação: uma casa decimal, ponto como separador; aferido na altura do umbigo"
label(data$abdcirc_c172954_chk)="Circunferência abdominal, expressos em centímetosvalidação: uma casa decimal, ponto como separador; aferido na altura do umbigo"
label(data$c124475)="Circunferência do braço dominante (cm)Definição: Uma medida circunferencial da maior parte do braço superiorValidação:expresso em centímetros; ponto como separador decimal e uma casa decimal"
label(data$c124475_chk)="Circunferência do braço dominante (cm)Definição: Uma medida circunferencial da maior parte do braço superiorValidação:expresso em centímetros; ponto como separador decimal e uma casa decimal"
label(data$anthro_chkerror)="Checks for different types results for the variables of interest"
label(data$anthro_chk)="Checks if: 1. all fields have values 2. confirmation fields are identical to source field  Results 1 if true or 0 if false"
label(data$bmi)="IMC (Kg/m²)"
label(data$weight_maxideal)="Peso ideal máximo"
label(data$weight_adjusted)="Peso ajustado"
label(data$kcal_kg20)="20 kcal/kg do Peso Ajustado"
label(data$kcal_kg22)="22 kcal/kg do Peso Ajustado"
label(data$dietaryenergy)="Oferta energética mais adequada para a intervenção nutricional"
label(data$wlkg)="Weight Loss (Kg)"
label(data$wl)="Weight Loss (%)"
label(data$acr_cm)="Adbominal circunference reduction (cm)"
label(data$acr)="Abdominal circunference reduction (%)"
label(data$bmir_dec)="BMI reduction (decimal points)"
label(data$bmir)="BMI Reduction (%)"
label(data$antropometria_complete)="Complete?"
label(data$bpbia_date)="Data e hora da abertura do formulário:"
label(data$bpbia_examiner)="Examinador"
label(data$bpbia_r_sw)=" Após o participante ter deitado na maca de forma confortável, deve-se iniciar a aferição da PA após 5 minutos de decúbito dorsal, e a realização da BIA após 10 minutos do início do tempo de decúbito. "
label(data$bp_r_c124475)="Tamanho do manguito apropriado "
label(data$bp_ra_s)="    1.1   Membro Superior Direito     mmHg   Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_ra_s   blood pressure, right arm, systolic    "
label(data$bp_ra_d)="    1.2   Membro Superior Direito     mmHg   Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_ra_d   blood pressure, right arm, diastolic    "
label(data$bp_ra_mean)="    1.3   Membro Superior Direito     mmHg   Pressão Arterial Média        Validação: 2 ou 3 números inteiros, sem decimal     bp_ra_mean   blood pressure, right arm, mean          Formula:   MAP = DBP + 1/3 * (SBP - DBP)     MAP   Mean arterial pressure     DBP   Diastolic blood pressure     SBP   Systolic Blood Pressure    "
label(data$bp_la_s)="    2.1   Membro Superior Esquerdo     mmHg   Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_la_s   blood pressure, left arm, systolic    "
label(data$bp_la_d)="    2.2   Membro Superior Esquerdo     mmHg   Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_la_d   blood pressure, left arm, diastolic    "
label(data$bp_la_mean)="    2.3   Membro Superior Esquerdo     mmHg   Pressão Arterial Média        Validação: 2 ou 3 números inteiros, sem decimal     bp_la_mean   blood pressure, left arm, mean          Formula:   MAP = DBP + 1/3 * (SBP - DBP)     MAP   Mean arterial pressure     DBP   Diastolic blood pressure     SBP   Systolic Blood Pressure    "
label(data$bp_reference)="    3   Membro de referência (membro com o maior valor de Pressão Arterial Média)     bp_reference   Reference member: member with highest mean arterial pressure     "
label(data$presso_arterial_determinao_do_membro_de_referncia_complete)="Complete?"
label(data$bp_datetime)="Data e hora da abertura do formulário:"
label(data$bp_examiner)="Examinador"
label(data$bp_sw)=" Após o participante ter deitado na maca de forma confortável, deve-se iniciar a aferição da PA após 5 minutos de decúbito dorsal, e a realização da BIA após 10 minutos do início do tempo de decúbito. "
label(data$bp_c49677)="Frequência cardíaca"
label(data$bp_c60832)="Saturação de O2 (%)"
label(data$bp_r11s)="    1.1   1ª medida        Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r11s   Blood pressure, reference member, 1st measurement, systolic    "
label(data$bp_r12d)="    1.2   1ª medida        Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r12d   Blood pressure, reference member, 1st measurement, diastolic    "
label(data$bp_r13m)="    1.3   1ª medida        Pressão arterial média        Validação: 2 ou 3 números inteiros, sem decimal     bp_r13m   Blood pressure, reference member, 1st measurement, mean    "
label(data$bp_sw_1st)="1st measurement, stopwatch"
label(data$bp_r21s)="    2.1   2ª medida        Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r21s   Blood pressure, reference member, 2nd measurement, systolic    "
label(data$bp_r21s_chk)="Confirm result     2.1   2ª medida        Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r21s   Blood pressure, reference member, 2nd measurement, systolic    "
label(data$bp_r22d)="    2.2   2ª medida        Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r22d   Blood pressure, reference member, 2nd measurement, diastolic    "
label(data$bp_r22d_chk)="Confirm result     2.2   2ª medida        Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r22d   Blood pressure, reference member, 2nd measurement, diastolic    "
label(data$bp_r23m)="    2.3   2ª medida        Pressão arterial média        Validação: 2 ou 3 números inteiros, sem decimal     bp_r23m   Blood pressure, reference member, 2nd measurement, mean    "
label(data$bp_sw_2nd)="2nd measurement, stopwatch"
label(data$bp_r31s)="    3.1   3ª medida        Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r31s   Blood pressure, reference member, 3rd measurement, systolic    "
label(data$bp_r31s_chk)="Confirm result     3.1   3ª medida        Pressão Arterial Sistólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r31s   Blood pressure, reference member, 3rd measurement, systolic    "
label(data$bp_r32d)="    3.2   3ª medida        Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r32d   Blood pressure, reference member, 3rd measurement, diastolic    "
label(data$bp_r32d_chk)="Confirm result     3.2   3ª medida        Pressão Arterial Diastólica        Validação: 2 ou 3 números inteiros, sem decimal     bp_r32d   Blood pressure, reference member, 3rd measurement, diastolic    "
label(data$bp_r33m)="    3.3   3ª medida        Pressão arterial média        Validação: 2 ou 3 números inteiros, sem decimal     bp_r33m   Blood pressure, reference member, 3rd measurement, mean    "
label(data$bp_diff)="Diferença entre a pressão sistólica da segunda e da terceira medida, em valor absoluto."
label(data$bp_sw_3rd)=" Realize outra medição em 60 seg "
label(data$bp_r41s)="    4.1   4ª medida        Pressão Arterial Sistólica        Validação: 2 ou 4 números inteiros, sem decimal     bp_r41s   Blood pressure, reference member, 4rd measurement, systolic    "
label(data$bp_r41s_chk)="Confirm result     4.1   4ª medida        Pressão Arterial Sistólica        Validação: 2 ou 4 números inteiros, sem decimal     bp_r41s   Blood pressure, reference member, 4rd measurement, systolic    "
label(data$bp_r42d)="    4.2   4ª medida        Pressão Arterial Diastólica        Validação: 2 ou 4 números inteiros, sem decimal     bp_r42d   Blood pressure, reference member, 4rd measurement, diastolic    "
label(data$bp_r42d_chk)="Confirm result     4.2   4ª medida        Pressão Arterial Diastólica        Validação: 2 ou 4 números inteiros, sem decimal     bp_r42d   Blood pressure, reference member, 4rd measurement, diastolic    "
label(data$bp_r43m)="    4.3   4ª medida        Pressão arterial média        Validação: 2 ou 4 números inteiros, sem decimal     bp_r43m   Blood pressure, reference member, 4rd measurement, mean    "
label(data$bp_mean_s)="Mean, systolic"
label(data$bp_stdev_s)="St. dev., systolic"
label(data$bp_mean_d)="Mean, diastolic"
label(data$bp_stdev_d)="St. dev., diastolic"
label(data$bp_mean_map)="Mean, MAP"
label(data$bp_stdev_map)="St. dev., MAP"
label(data$bp_showmetadata)="Mostrar metadados?"
label(data$presso_arterial_complete)="Complete?"
label(data$bia_rawfiles)="BIA Raw Files"
label(data$bia_datetime)="Data e hora da abertura do formulário:"
label(data$bia_examiner)="Examinador"
label(data$bia_tobacco)="Fumou ao menos um cigarro nas últimas 24 horas"
label(data$bia_phact)="Fez atividade física intensa nas ultimas 24 horas:"
label(data$bia_alcohol)="Fez o uso de bebida alcoólicas nas ultimas 24 horas:"
label(data$bia_ambtemp)="Temperatura ambiente entre 23-25°C:"
label(data$bia_axtemp)="Temperatura axilar:"
label(data$bia_clothes)="Paciente com roupas leves:"
label(data$bia_objects)="Remover objetos metálicos:"
label(data$bia_hair)="Presença de pelos na topografia de adesão dos eletrodos:"
label(data$bia_hair_rem)="Remoção dos pelos com a lamina de barbear descartável:"
label(data$bia_cleaning)="Limpeza da pele com álcool 70%:"
label(data$bia_lastfood)="Horário da última ingestão de alimentos"
label(data$bia_lastliquid)="Horário da última ingestão de líquidos"
label(data$bia_decubitus)="Paciente em decúbito dorsal por ao menos 10 minutos:"
label(data$bia_time)="Horário exato da realização da BIA"
label(data$bia_fastingfood)="Tempo de jejum de alimentos, em horas"
label(data$bia_fastingliquid)="Tempo de jejum, em horas"
label(data$resistance)="Resistance / Resistência Ω (R)"
label(data$resistance_chk)="Confirm Value Resistance / Resistência Ω (R)"
label(data$reactance)="Reatância Ω (Xc)"
label(data$reactance_chk)="Confirm Value: Reatância Ω (Xc)"
label(data$pha)="Phase Angle / Ângulo de fase º (PhA)"
label(data$pha_chk)="Confirm Value: Phase Angle / Ângulo de fase º (PhA)"
label(data$bia_showmetadata)="Mostrar metadados?"
label(data$impedncia_bioeltrica_corporal_complete)="Complete?"
label(data$grip_limitations)="Existe alguma limitação visível nas mãos?"
label(data$grip_rhlimitation)="Critérios de exclusão: limitações visíveis na mão direita"
label(data$grip_lhlimitation___0)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Nenhuma)"
label(data$grip_lhlimitation___1)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Paralisia da mão)"
label(data$grip_lhlimitation___2)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Usando gesso no pulso ou na mão)"
label(data$grip_lhlimitation___3)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=A maior parte da mão coberta por bandagens)"
label(data$grip_lhlimitation___4)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Ausência do polegar ou dedos quebrados)"
label(data$grip_lhlimitation___5)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Outra limitação significativa {grip_lhlimitother})"
label(data$grip_lhlimitation___ni)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=No information)"
label(data$grip_lhlimitation___unk)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Unknown)"
label(data$grip_lhlimitation___nask)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Not asked)"
label(data$grip_lhlimitation___asku)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Asked but unknown)"
label(data$grip_lhlimitation___inv)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Invalid)"
label(data$grip_lhlimitation___na)="Critérios de exclusão: limitações visíveis na mão esquerda (choice=Not applicable)"
label(data$griprecentsurgery)="2. Você fez alguma cirurgia nas mãos ou pulsos nos últimos 3 meses?"
label(data$grip_exclude)="3. Neste teste, iremos pedir para que você aperte o aparelho o mais forte que consiga. Existe algum motivo pelo qual você não poderia fazer o teste?"
label(data$grip_surgery)="Condições não excludentes: 1. Você já fez alguma cirurgia nas mãos ou nos pulsos devido a artrite ou síndrome do túnel do carpo?"
label(data$grip_dominance)="2. Você é destro, canhoto ou ambidestro"
label(data$grip_pain)="3. Você teve alguma dor, sensação de cansaço ou rigidez em alguma das mãos nos últimos 7 dias?"
label(data$grip_rhpain)="3.1 Mão direita:A dor, sensação de cansaço ou rigidez na sua mão direita é causada por artrite, tendinite ou síndrome do túnel do carpo?"
label(data$grip_lhpain)="3.1 Mão esquerda: A dor, sensação de cansaço ou rigidez na sua mão direita é causada por artrite, tendinite ou síndrome do túnel do carpo?"
label(data$grip_procedure)=" Conduzindo um teste prático  - Objetivo: garantir que o participante compreende como o teste será realizado - O teste NÃO deve ser realizado com força máxima - Realize o teste com a mão oposta àquela que será a primeira mão testada.Obs: Se apenas uma mão for elegível para o teste, o teste prático será realizado com essa mão, com um lembrete para aguardar 60 segundos antes de começar o teste. Utilize um cronômetro digital para garantir que aguarde 60 segundos antes de iniciar o teste. - Com o participante em pé, confirme a postura adequada:  Ficar em pé com os pés afastados na largura do quadril, alinhados e os dedos dos pés apontando para frente. Joelhos confortáveis, mas não dobrados. Ombros para trás e peito erguido. Cabeça nivelada. Olhos direcionados para frente. Braço ao lado do corpo com a palma da mão voltada para a perna. Nem o dinamômetro nem a mão devem tocar o corpo.  - Agora tente uma vez apenas para sentir como é. Para esse treino, aperte suavemente. Pronto, inspire, expire e aperte suavemente durante a expiração.  O teste foi realizado com sucesso e o participante entendeu as orientações? "
label(data$grip_rh1)="Mão direita: medida 1"
label(data$grip_rh1check)="Mão direita: validação 1"
label(data$gripsw_rh1)="Mão direita: stopwatch 1"
label(data$grip_lh1)="Mão esquerda: medida 1"
label(data$grip_lh1check)="Mão esquerda: validação 1"
label(data$gripsw_lh1)="Mão esquerda: stopwatch 1"
label(data$grip_rh2)="Mão direita: medida 2 "
label(data$grip_rh2check)="Mão direita: validação 2 "
label(data$gripsw_rh2)="Mão direita: stopwatch 2 "
label(data$grip_lh2)="Mão esquerda: medida 2 "
label(data$grip_lh2check)="Mão esquerda: validação 2 "
label(data$gripsw_lh2)="Mão esquerda: stopwatch 2"
label(data$grip_rh3)="Mão direita: medida 3 "
label(data$grip_rh3check)="Mão direita: validação 3 "
label(data$grip_lh3)="Mão esquerda: medida 3 "
label(data$grip_lh3check)="Mão esquerda: validação 3 "
label(data$grip_rhmean)="Média da mão direita (kg):"
label(data$grip_rhstdev)="Desvio padrão da mão direita:"
label(data$grip_lhmean)="Média da mão esquerda (kg):"
label(data$grip_lhstdev)="Desvio padrão da mão esquerda:"
label(data$grip_seemetadata)="Ver metadados?"
label(data$fora_de_preenso_palmar_complete)="Complete?"
label(data$habitointestinal)="Qual a frequência do seu hábito intestinal? "
label(data$consist_ncia)="Com que regularidade você tem evacuações com consistência firme? "
label(data$evacuacaoliquida)="Com que regularidade você tem evacuações líquidas ou soltas?"
label(data$constipacao)="Você já sofreu de constipação (dificuldade para evacuar)?  "
label(data$laxativos)="Com que frequência você precisa fazer uso de laxantes para estimular as evacuações?"
label(data$frequenciaurinaria)="Frequência urinária: "
label(data$ingestaohidrica)="Em relação à quantidade de água consumida durante o dia:"
label(data$quedadecabelo)="Você tem observado queda de cabelo recentemente? "
label(data$avaliao_nutricional_complete)="Complete?"
label(data$foodallergy)="Possui alergia e/ou intolerâncias alimentares?"
label(data$amendoim)="Alergia ao amendoim"
label(data$alergianozes)="Alergia às nozes (como castanhas, amêndoas, pistaches)"
label(data$alergiamar)="Alergia a frutos do mar (como camarão, caranguejo, lagosta)"
label(data$alergia_a_ovos)="Alergia a ovos"
label(data$intoler_ncia_a_lactose)="Alergia e/ou intolerância a laticínios"
label(data$alergia_ao_trigo_gl_ten_ce)="Alergia ao trigo/glúten (celíacos)"
label(data$lergia_soja)="Alergia à soja"
label(data$alergia_a_peixes_como_salm)="Alergia a peixes (como salmão, atum, bacalhau)"
label(data$alergia_alimentar_complete)="Complete?"
label(data$evs_days)="Script:Em média, em quantos dias por semana você realiza atividade física moderada a extenuante, como uma caminhada rápida?"
label(data$evs_time)="Script: Em média, por quantos minutos por dia você realiza atividade física neste nível?(expresso em minutos)"
label(data$evs_score)=" Escore EVS "
label(data$phy_activity_1)="Qual a atividade física principal realizada pelo participante?"
label(data$phy_activity_2)="O participante realiza alguma atividade física secundária?"
label(data$phy_activity_3)="O participante realiza alguma atividade física terciária?"
label(data$exercise_vital_sign_complete)="Complete?"
label(data$alcoholhistory)="O participante consome bebidas alcoólicas frequentemente?"
label(data$alcoholstoppedage)="Parou de beber há quantos anos?"
label(data$alcoholyears)="Há quantos anos o participante consome álcool?"
label(data$alcoholtype___1)="Tipo de bebida alcoólica consumida (choice=Cerveja)"
label(data$alcoholtype___2)="Tipo de bebida alcoólica consumida (choice=Vinho)"
label(data$alcoholtype___3)="Tipo de bebida alcoólica consumida (choice=Cachaça, whisky ou vodka)"
label(data$alcoholtype___9)="Tipo de bebida alcoólica consumida (choice=Outro (especificar))"
label(data$alcoholtype___ni)="Tipo de bebida alcoólica consumida (choice=No information)"
label(data$alcoholtype___unk)="Tipo de bebida alcoólica consumida (choice=Unknown)"
label(data$alcoholtype___nask)="Tipo de bebida alcoólica consumida (choice=Not asked)"
label(data$alcoholtype___asku)="Tipo de bebida alcoólica consumida (choice=Asked but unknown)"
label(data$alcoholtype___inv)="Tipo de bebida alcoólica consumida (choice=Invalid)"
label(data$alcoholtype___na)="Tipo de bebida alcoólica consumida (choice=Not applicable)"
label(data$beer)="Quantas latas por semana? (1 lata = 350 ml)"
label(data$beerdose)="Doses por semana"
label(data$wine)="Quantos ml por semana? (1 garrafa = 750 ml)"
label(data$winedose)="Doses por semana"
label(data$destilled)="Quantos ml por semana? (1 dose = 40 ml / 1 corote = 500 ml)"
label(data$destilleddose)="Doses por semana"
label(data$alcoholtypeother)="Outro (favor especificar)"
label(data$alcoholtypeotherdose)="Quantas doses por semana? (1 dose = 14g de álcool) "
label(data$alcoholtotal)="Consumo total de álcool por semana, expresso em doses (1 dose = 14g de etanol)"
label(data$alcoholsignificant)="Consumo significativo?1 = consumo significativo de álcool0 = consumo não significativo de álcool"
label(data$consumo_alcool_complete)="Complete?"
label(data$smokehistory)="Histórico de tabagismo: Fumou pelo menos 100 cigarros  (5 maços) durante a vida?"
label(data$smokeagestart)="Idade que começou a fumar (anos):"
label(data$smokeyears)="Número de anos em que fumou cigarros? (anos)"
label(data$cigarettesday)="Número médio de cigarros por dia?"
label(data$packyears)="Anos-maço"
label(data$smokeagequit)="Idade parou de fumar? (anos)"
label(data$consumo_tabaco_complete)="Complete?"
label(data$horario)="Horário: "
label(data$horario_2)="Horário: "
label(data$horario_3)="Horário: "
label(data$horario_4)="Horário: "
label(data$horario_5)="Horário: "
label(data$horario_6)="Horário: "
label(data$alimento)="Alimento:"
label(data$alimento_2)="Alimento:"
label(data$alimento_3)="Alimento:"
label(data$alimento_4)="Alimento:"
label(data$alimento_5)="Alimento:"
label(data$alimento_6)="Alimento:"
label(data$obs)="Observações: "
label(data$obs_2)="Observações: "
label(data$obs_4)="Observações: "
label(data$obs_3)="Observações: "
label(data$obs_5)="Observações: "
label(data$obs_6)="Observações: "
label(data$pdf_upload)="PDF upload "
label(data$recordatrio_alimentar_complete)="Complete?"
label(data$whatmeals___1)="Marque as refeições que o participante faz (choice=Café da manhã)"
label(data$whatmeals___2)="Marque as refeições que o participante faz (choice=Lanche da manhã)"
label(data$whatmeals___3)="Marque as refeições que o participante faz (choice=Almoço)"
label(data$whatmeals___4)="Marque as refeições que o participante faz (choice=Lanche da tarde)"
label(data$whatmeals___5)="Marque as refeições que o participante faz (choice=Jantar)"
label(data$whatmeals___6)="Marque as refeições que o participante faz (choice=Ceia)"
label(data$whatmeals___ni)="Marque as refeições que o participante faz (choice=No information)"
label(data$whatmeals___unk)="Marque as refeições que o participante faz (choice=Unknown)"
label(data$whatmeals___nask)="Marque as refeições que o participante faz (choice=Not asked)"
label(data$whatmeals___asku)="Marque as refeições que o participante faz (choice=Asked but unknown)"
label(data$whatmeals___inv)="Marque as refeições que o participante faz (choice=Invalid)"
label(data$whatmeals___na)="Marque as refeições que o participante faz (choice=Not applicable)"
label(data$totalkcal)="INGESTÃO CALÓRICA TOTAL (kcal):"
label(data$carboidratos_v2)="Carboidratos em gramas:"
label(data$kcal_cho_v2)="Kcal de CHO:"
label(data$kcal_ptn_v2)="Kcal de proteína:"
label(data$kcal_lip_v2)="Kcal de lipídeo:"
label(data$proteina_v2)="Proteínas em gramas: "
label(data$lipideos_v2)="Lipídeos em gramas:  "
label(data$gramascho_manha_v2)="Gramas Carboidrato manhã"
label(data$gramasptn_manha_v2)="Gramas proteina manha:"
label(data$gramaslip_manha_v2)="Gramas lipideos manha:"
label(data$gramaslip_lanchemanha_v2)="Gramas lipideos lanche da manha:"
label(data$gramascho_lanchemanha_v2)="Gramas carboidratos lanche da manha:"
label(data$gramasptn_lanchemanha_v2)="Gramas proteinas lanche da manha:"
label(data$gramascho_almoco_v2)="Gramas carboidratos almoço"
label(data$gramaslip_almoco_v2)="Gramas lipideos almoço"
label(data$gramasptn_almoco_v2)="Gramas proteinas almoço"
label(data$gramascho_tarde_v2)="Gramas carboidratos lanche da tarde:"
label(data$gramaslip_tarde_v2)="Gramas lipideos lanche da tarde:"
label(data$gramasptn_tarde_v2)="Gramas proteinas lanche da tarde:"
label(data$gramaslip_jantar_v2)="Gramas lipideos jantar:"
label(data$gramasptn_jantar_v2)="Gramas proteinas jantar:"
label(data$gramascho_jantar_v2)="Gramas carboidratos jantar:"
label(data$gramascho_lanchenoturno_v2)="Gramas carboidratos lanche noturno:"
label(data$gramaslip_lanchenoturno_v2)="Gramas lipideos lanche noturno:"
label(data$gramasptn_lanchenoturno_v2)="Gramas proteinas lanche noturno:"
label(data$kcalcho_manha_v2)="Carboidratos em calorias café da manhã"
label(data$kcalptn_manha_v2)="Proteinas em calorias café da manhã"
label(data$kcallip_manha_v2)="Lipídeos em calorias café da manhã"
label(data$kcaltotal_manha_v2)="Calorias totais café da manhã"
label(data$kcalcho_lanchemanha_v2)="Carboidratos em calorias lanche da manhã"
label(data$kcallip_lanchemanha_v2)="Lipídeos em calorias lanche da manhã"
label(data$kcalptn_lanchemanha_v2)="Proteínas em calorias lanche da manhã"
label(data$kcaltotal_lanchemanha_v2)="Calorias totais lanche da manhã"
label(data$kcaltotal_almoco_v2)="Calorias totais no almoço"
label(data$kcalcho_almoco_v2)="Carboidratos em calorias no almoço"
label(data$kcallip_almoco_v2)="Lipídeos em calorias no almoço"
label(data$kcalptn_almoco_v2)="Proteinas em calorias no almoço"
label(data$kcalcho_tarde_v2)="Carboidratos em calorias no lanche da tarde"
label(data$kcallip_tarde_v2)="Lipídeos em calorias no lanche da tarde"
label(data$kcalptn_tarde_v2)="Proteínas em calorias no lanche da tarde"
label(data$kcaltotal_tarde_v2)="Calorias totais no lanche da tarde"
label(data$kcalcho_jantar_v2)="Carboidratos em calorias no jantar"
label(data$kcalptn_jantar_v2)="Proteínas em calorias no jantar"
label(data$kcallip_jantar_v2)="Lipídeos em calorias no jantar"
label(data$kcaltotal_jantar_v2)="Calorias totais no jantar"
label(data$kcalcho_lanchenoturno_v2)="Carboidratos em calorias no lanche noturno"
label(data$kcalptn_lanchenoturno_v2)="Proteínas em calorias no lanche noturno"
label(data$kcallip_lanchenoturno_v2)="Lipídeos em calorias no lanche noturno"
label(data$kcaltotal_lanchenoturno_v2)="Calorias totais no lanche noturno"
label(data$nutriumpdf)="Adicione o PDF"
label(data$avaliao_da_ingesto_alimentar_complete)="Complete?"
label(data$c83129_yn)="O participante já iniciou o uso das cápsulas da intervenção designadas?"
label(data$visit1_schedule)="Data agendada 1visit"
label(data$wk_removealert)="Remover alerta semanal?"
label(data$c83129)="Data do início da intervenção"
label(data$date_45d)="Data que completa 45 dias"
label(data$visit2_schedule)="Data agendada 2ªV"
label(data$date_90d)="Data que completa 90 dias"
label(data$visit3_schedule)="Data agendada 3ªV"
label(data$link_datasimportantes)="@HIDDEN field containing link to form: datas importantes"
label(data$datas_importantes_complete)="Complete?"
label(data$c83083)="Identificador do participante"
label(data$c142660)="Random Allocation Group"
label(data$nmero_do_participante_complete)="Complete?"
label(data$comorbidity)="O participante [eleg_arm_1][record_id]relata ter alguma comorbidade?"
label(data$comorbidity_2)="Mais algum dado relevante?"
label(data$c16457)="Comorbidades mais comuns"
label(data$com_howlong)="Há quanto tempo foi feito o diagnóstico"
label(data$com_howlong2)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$com_concat)="Comorbidades já listadas"
label(data$comorbidities_metadata)="Metadata (NCIT: C52095) All medical conditions and drug names are coded according to NCIT Ontology, version 23.06d (2023-06-26)"
label(data$comorbidades_complete)="Complete?"
label(data$medication)="O participante [eleg_arm_1][record_id]faz uso atual de algum medicamento?"
label(data$medication_2)="Mais algum dado relevante?"
label(data$c459)="Medicamentos mais comuns"
label(data$c64493)="Posologia"
label(data$drug_howlong)="Há quanto tempo utiliza o medicamento?"
label(data$drug_howlong_2)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$drug_info)="@DEFAULT=un. por dose @HIDDEN"
label(data$drug_howmany)="Quantas unidades de Comp./Cáps. por dose"
label(data$drugs_concat)="Medicamentos já listados"
label(data$takes_other_medication)="Outros medicamentos em uso"
label(data$medications_metadata)="Metadata (NCIT: C52095) All medical conditions and drug names are coded according to NCIT Ontology, version 23.06d (2023-06-26)"
label(data$medicamentos_de_uso_habitual_complete)="Complete?"
label(data$medicationprevious)="O participante [eleg_arm_1][record_id] fazia uso de algum medicamento que foi suspenso ou abandonada?"
label(data$medicationprevious_2)="Mais algum dado relevante?"
label(data$c460)="Medicamentos mais comuns"
label(data$prev_drugs_info)="Iniciado há:"
label(data$c87865)="Há quanto tempo o medicamento foi iniciado?"
label(data$c87865_2)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$prev_drugs_info_2)="Suspenso há"
label(data$c83047)="Há quanto tempo o medicamento foi suspenso?"
label(data$c83047_2)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$previousdrugs_concat)="Medicamentos já listados"
label(data$other_medication)="Outros medicamentos"
label(data$medicamentos_prvios_complete)="Complete?"
label(data$medicalhistory)="O participante [eleg_arm_1][record_id]tem algum antecedente médico relevante?Cirurgias, internações, doenças graves"
label(data$medicalhistory_2)="Mais algum dado relevante?"
label(data$c16458)="Antecedentes mais comuns"
label(data$c18772)="Antecedentes Pessoais (NCIT)"
label(data$c18772_notes)="Antecedentes Pessoais (Notas)"
label(data$c65140)="Há quanto tempo?"
label(data$c65140_2)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$pmh_concat)="Antecedentes já listados"
label(data$antecedentes_pessoais_complete)="Complete?"
label(data$c4876_yn)="O participante [eleg_arm_1][record_id] tem algum sintoma?"
label(data$c4876_yn_2)="Mais algum dado relevante?"
label(data$c4876_instance)="Instance number"
label(data$c4876)="Symptom (Code C4876)"
label(data$c25685)="Specify (Code C25685)"
label(data$c42619)="Note (Code C42619)"
label(data$info)="@DEFAULT=/ Onset: @HIDDEN  Used in concatenation "
label(data$c124353)="Symptom Onset (Code C124353)"
label(data$c124353_unitoftime)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$info_2)="@DEFAULT=/ Severity: @HIDDEN  Used in concatenation "
label(data$c120071)="Severity of Symptom Likert Scale (Code C120071) A scale for the subjective scoring of symptoms that ranges from 0: Not Present to 10: As Bad as You Can Imagine."
label(data$info_3)="@DEFAULT=/ @HIDDEN  Used in concatenation "
label(data$c25471)="Current (Code C25471) Asks if the related symptom is current or has come to a resolution "
label(data$c178992)="Symptom Resolution Date (Code C178992)"
label(data$c178992_unitoftime)="Unit of Time (Code C42574)    1 Year C29848   2 Day C25301   3 Month C29846   4 Week C29844   "
label(data$info_4)="@IF([event-number] >= 2,@DEFAULT=/ Assessment of causality:,) @HIDDEN  Used in concatenation "
label(data$c41332)="   Existe possibilidade razoável de nexo causal com a intervenção?{c41332_link_ae}   "
label(data$sym_ncit_concat)="CONCAT"
label(data$sintomas_complete)="Complete?"
label(data$phyex_finding_yn)="O participante [eleg_arm_1][record_id] apresenta alguma alteração no exame físico?"
label(data$phyex_finding_yn_2)="Mais algum dado relevante?"
label(data$c25305_system)="System"
label(data$c87079)="       General Apperance       "
label(data$c163004)="       Oral ExaminationOral Cavity Finding (Code C60925)       "
label(data$c168436)="       Skin ExaminationIntegumentary System Finding (Code C36281)       "
label(data$c122008)="        Cardiovascular ExaminationCardiovascular System Finding (Code C35552)        "
label(data$c198356)="        Respiratory System ExaminationRespiratory System Finding (Code C45233)        "
label(data$c167415)="        Abdominal ExaminationDigestive System Finding (Code C36279)        "
label(data$c168189)="        Examination of Extremities        "
label(data$c83023)="Abnormal Finding Description (NCIT) "
label(data$c83023_notindexed)="Description of abnormal non-indexed findings ORAnnotations for indexed findings"
label(data$phyexam_concat)="Concatenates data collected from PREVIOUS instance"
label(data$phyexam_concat2)="Concatenated data from the variable: phyexam_concat, which means that it will collect all concatenated data from the current instance -2."
label(data$exame_fsico_complete)="Complete?"
label(data$lab_list_yn)="Mostrar a lista de exames a serem solicitados?"
label(data$lab_request_pdf_1)="Faça o upload do pedido assinado do exame"
label(data$lab_request_pdf_2)="Faça o upload do protocolo do pedido de exame em que constam data e local de coleta"
label(data$data_consulta_agendamento)="Data da consulta médica criada no RKM para agendamento dos exames laboratoriais"
label(data$eleg2_labrequest)="Data em que foi feita a solicitação dos exames laboratoriais:"
label(data$eleg2_labschedule)="Data agendada para coleta"
label(data$eleg2_whichlab)="Qual o local agendado para coleta?"
label(data$lab_coleta)="Data em que os exames foram efetivamente coletados"
label(data$c64548)="Proteína C Reativa (mg/L)"
label(data$c64467)="AST, Aspartato aminotransferase (U/L) / TGO, Transaminase Oxalacética  (U/L)"
label(data$c64433)="ALT, Alanina Aminotransferase (U/L) / TGP, Transaminase Pirúvica  (U/L)"
label(data$c64847)="Gama-glutamiltransferase (U/L)"
label(data$c64432)="Fosfatase alcalina (U/L)"
label(data$c38037)="Bilirrubina total (mg/dL)"
label(data$c64481)="Bilirrubina direta (mg/dL)"
label(data$c64483)="Bilirrubina indireta (mg/dL)"
label(data$c64434)="Amilase (U/L)"
label(data$c64858)="Proteínas totais (g/dL)"
label(data$c64431)="Albumina (g/dL)"
label(data$c64815)="Ureia (mg/dL)"
label(data$c61023)="Creatinina (mg/dL)"
label(data$c90505)="Taxa de filtração glomerular (mL/min/1.73m²)"
label(data$c64489)="CPK, Creatinofosfoquinase (U/L)"
label(data$c61034)="Ácido úrico (mg/dL)"
label(data$c61029)="Sódio (mEq/L)"
label(data$c61030)="Potássio (mEq/L)"
label(data$c81948)="Cálcio iônico (mmol/L"
label(data$c61032)="Colesterol total (mg/dL)"
label(data$c61042)="LDL (mg/dL)"
label(data$c64849)="Hemoglobina glicosilada A1c (%)"
label(data$c61037)="Triglicerídeos (mg/dL)"
label(data$c61041)="HDL (mg/dL)"
label(data$c61027)="Glicemia de jejum (mg/dL)"
label(data$c74788)="Insulina (uIU/mL); (uIU/mL x 7,17 = pmol/L)"
label(data$c100447)="HOMA-IR"
label(data$c123459)="QUICK < 0.34: Probable insulin resistense QUICKI = QUICK INDEX (Quantitative Insulin sensitivity Check Index) Insulin Sensitivity Measurement (Code C123459)"
label(data$c17479)="Beta-HCG"
label(data$c64848)="Hemoglobina (g/dL)"
label(data$c64796)="Hematócrito (%)"
label(data$c51948)="Leucócitos (×10³/mm³)"
label(data$c51951)="Plaquetas (×10³/mm³)"
label(data$c81295)="TSH (µIU/mL) "
label(data$c74786)="T4 livre Free Thyroxine Measurement (Code C74786)"
label(data$lab_pdf)="Anexe o arquivo em PDF do exame laboratorial"
label(data$other_lab_yn)="Outros exames relevantes OU anotações sobre os exames realizados"
label(data$other_lab)="Outros exames relevantes OU notas / comentários"
label(data$lab_chk)="Auditoria - resultados conferidos?"
label(data$lab_metadata)="Metadata (NCIT: C52095)All variable names are coded according to NCIT Ontology version 23.06d (2023-06-26)"
label(data$exames_laboratoriais_complete)="Complete?"
label(data$ecg_datetime)="Data e hora:"
label(data$ecg_done)="O exame foi realizado?"
label(data$ecg_notdone)="Reason for not performing ECG"
label(data$ecg_upload)="Faça o upload do arquivo em PDF do exame"
label(data$ecg_standard)="Padronização: Amplitude 10 mm/1 mV;Velocidade 25 mm/s"
label(data$c49677)="HR (Frequência cardíaca); bpm:"
label(data$sampletime)="Sample time (seg)"
label(data$c62087)="QRS Interval (Duração do segmento QRS), ms: "
label(data$c83502)="PR Interval (Duração do intervalo PR); ms:"
label(data$c83501)="QT Interval (Duração do intervalo QT), ms:"
label(data$c100391)="QTc interval (Duração do intervalo QTc), ms:"
label(data$c118165)="QRS axis (Eixo), graus:"
label(data$c87081)="Rhythm"
label(data$c168100___0)="ECG findings (choice=None)"
label(data$c168100___c62269)="ECG findings (choice=LBBB)"
label(data$c168100___c62270)="ECG findings (choice=RBBB)"
label(data$c168100___c26703)="ECG findings (choice=AV block)"
label(data$c168100___c71026)="ECG findings (choice=ST segment changes)"
label(data$c168100___c191644)="ECG findings (choice=Abnormal Q waves)"
label(data$c168100___c62271)="ECG findings (choice=Nonspecific intraventricular conduction delay)"
label(data$c168100___ni)="ECG findings (choice=No information)"
label(data$c168100___unk)="ECG findings (choice=Unknown)"
label(data$c168100___nask)="ECG findings (choice=Not asked)"
label(data$c168100___asku)="ECG findings (choice=Asked but unknown)"
label(data$c168100___inv)="ECG findings (choice=Invalid)"
label(data$c168100___na)="ECG findings (choice=Not applicable)"
label(data$ecg_prompt)="Prompt (copie e cole o conteúdo da caixa de texto no canto inferior direito da página do ECG)"
label(data$ecg_audit)="Auditoria dos dados (exclusivo para o pesquisador principal) Audit (NCIT: C45269)"
label(data$c117807)="ECG Technical Quality (NCIT: C117807)"
label(data$ecg_checked_yn)="Checked wave measurement on software?"
label(data$ecg_metadata_yn)="Ver metadados?"
label(data$eletrocardiograma_complete)="Complete?"
label(data$adhere_1)="Você tem tomado o medicamento do estudo conforme foi prescrito e orientado?"
label(data$adhere_2)="Como você toma o medicamento? Quantas cápsulas, em quais horários?"
label(data$adhere_2_2)="Outra forma de tomar a medicação (especifique)"
label(data$adhere_3)="Como você se lembra de tomar o medicamento? Você usa algum tipo de lembrete (alarmes, estojos de remédios, etc.)?"
label(data$adhere_3_3)="Outras formas de lembrete (especifique)"
label(data$adhere_4)="Você perdeu alguma dose do medicamento do estudo?"
label(data$adhere_4_1)="Quantas vezes você perdeu alguma dose do medicamento do estudo?"
label(data$adhere_4_2)="Em quais momentos você perdeu as dose do medicamento do estudo?"
label(data$adhere_4_3)="Outros momentos em que perdeu as doses (especificar)"
label(data$adhere_5)="Em algum momento durante o estudo, você parou de tomar o medicamento?"
label(data$adhere_5_1)="Se sim, por quantos dias?"
label(data$adhere_5_2)="Se sim, por quê?"
label(data$adhere_5_3)="Outra justificativa para ter parado a medicação (especificar)"
label(data$adhere_6)="Você já ficou sem o medicamento do estudo alguma vez porque as cápsulas acabaram antes de pegar a reposição?"
label(data$adhere_6_1)="Motivo para ter ficado sem o medicamento"
label(data$adhere_7)="Houve alguma mudança em sua rotina diária que pode afetar sua capacidade de tomar o medicamento de forma consistente?"
label(data$adhere_7_1)="Mudança na rotina que afeta a tomada (especificar)"
label(data$adhere_8)="Você está percebendo alguma melhoria em sua condição que atribui ao medicamento do estudo?"
label(data$adhere_8_1)="Especifique as melhorias relatadas (no caso de sintomas, inserir no instrumento específico)"
label(data$adhere_10)="Você está enfrentando algum desafio que atrapalha a tomada do medicamento?"
label(data$adhere_10_1)="Especifique os desafios que atrapalham na tomada"
label(data$adhere_11)="Em uma escala de 1 a 10, quão confiante você está em seguir o cronograma de medicamentos?"
label(data$adhere_12)="Como você classificaria sua adesão geral ao medicamento do estudo? (opções: ruim, regular, boa, excelente)"
label(data$adeso_complete)="Complete?"
label(data$ae_evaluation_date)="Adverse Event Evaluation Date"
label(data$ae_yes_no)="Algum Evento Adverso neste ciclo?"
label(data$sae)="Evento Adverso Grave? "
label(data$adverse_event)="Evento Adverso"
label(data$ae_description)="Descrição"
label(data$aes)="Classificação"
label(data$grade)="Grau"
label(data$start_date)="Início"
label(data$stop_date)="Término"
label(data$attribution)="Atribuição de causalidade"
label(data$action_taken)="Ação Realizada"
label(data$seguimento)="Seguimento"
label(data$additional_aes)="Eventos Adversos Adicionais?"
label(data$ae_concatenate)="Evento adverso"
label(data$eventos_adversos_complete)="Complete?"
label(data$md_date)="Data"
label(data$md_pipe_com)="Comorbidities"
label(data$bia_diuretic)="Faz uso de diurético?"
label(data$bia_dosechange)="Houve mudança na dose de diurético nos últimos 3 meses?"
label(data$md_pipe_drugs)="Medicações em uso atual"
label(data$md_pipe_prevdrugs)="Medicamentos utilizados previamente"
label(data$md_pipe_pmh)="Antecedentes Médicos"
label(data$bia_menses)="A participante menstrua?"
label(data$bia_mensesreg)="Ciclo menstrual regular?"
label(data$bia_cycleduration)="Duração do ciclo menstrual (O ciclo menstrual tem uma duração média de 28 dias)"
label(data$bia_lastmenses)="Data da última menstruação"
label(data$bia_ovulation_1)="Nº de dias depois da DUM que a pessoa vai ovular"
label(data$bia_ovulationdate)="Data da próxima ovulação"
label(data$bia_nextmenses)="Data da próxima menstruação"
label(data$bia_menstrualcy)="Fase do ciclo menstrual"
label(data$md_drugs)="Alguma mudança nos MEU ou dosagem?"
label(data$md_drugs_note)="Notas"
label(data$md_pipesym1st)="Piping sintomas 1ª visita"
label(data$md_pipesym2nd)="Piping sintomas 2ª visita"
label(data$md_pipesym3rd)="Piping sintomas 3ª visita"
label(data$phy_exam_1st)="Exame físico 1ª visita, concatenação das variáveis: phyexam_concat e phyexam_concat2"
label(data$phy_exam_2nd)="Exame físico 2ª visita, concatenação das variáveis: phyexam_concat e phyexam_concat2"
label(data$phy_exam_3rd)="Exame físico 3ª visita, concatenação das variáveis: phyexam_concat e phyexam_concat2"
label(data$md_show_pipelab)="Show lab?"
label(data$md_labs)="Algum exame de laboratório para checar nesta visita?"
label(data$md_labswhynot)="Por que não?"
label(data$md_labs_chked)="Exames checados?"
label(data$md_labs_find)="Algum achado anormal?"
label(data$md_labs_find_mng)="Notas e conduta em relação a achados laboratoriais anormais"
label(data$md_bottle)="Algum motivo impede uso da intervenção?"
label(data$md_reasonwhynot)="Specify reasons preventing delivery of the medication?"
label(data$md_deliver)="Intervenção entregue ao paciente?"
label(data$md_deliver_no)="Explique o motivo"
label(data$md_deliver_date)="Data de entrega da intervenção"
label(data$md_explain)="Explicado sobre a forma correta de uso?"
label(data$md_explainchk)="Participante tem total compreensão sobre o uso?"
label(data$md_understand_no)="Notas"
label(data$c133396)="Data prevista para o início do uso das cápsulas {c133396_note}"
label(data$c133396_note)="Data prevista para o início do uso das cápsulas"
label(data$c133396_labsdelay)="O início da intervenção está programado para após a coleta dos exames laboratoriais?"
label(data$md_mng_yn)="Outras notas / condutas?"
label(data$md_mng)="Outras notas ou condutas"
label(data$avaliao_mdica_complete)="Complete?"
label(data$contato_semanal_timestamp)="Survey Timestamp"
label(data$wk_isform)="Detects if the current instrument is being viewed as a data entry form (returns 1 for True, 0 for False),"
label(data$wk_interviewer)="Entrevistador"
label(data$wk_datetime1)="{wk_interviewer}Data e hora da primeira tentativa de contato: Contato bem sucedido? {wk_datetime1_yn}"
label(data$wk_datetime1_yn)="Contato bem sucedido?"
label(data$wk_datetime2)="Data e hora da segunda tentativa de contato: Contato bem sucedido? {wk_datetime2_yn}"
label(data$wk_datetime2_yn)="Contato bem sucedido?"
label(data$wk_datetime3)="Data e hora da terceira tentativa de contato: Contato bem sucedido? {wk_datetime3_yn}"
label(data$wk_datetime3_yn)="Contato bem sucedido?"
label(data$wk_datetime4)="Data e hora da quarta tentativa de contato: Contato bem sucedido? {wk_datetime4_yn}"
label(data$wk_datetime4_yn)="Contato bem sucedido?"
label(data$wk_datetime5)="Data e hora da quintatentativa de contato: Contato bem sucedido? {wk_datetime5_yn}"
label(data$wk_datetime5_yn)="Contato bem sucedido?"
label(data$wk_datetime6)="Data e hora da sexta tentativa de contato: Contato bem sucedido? {wk_datetime6_yn}"
label(data$wk_datetime6_yn)="Contato bem sucedido?"
label(data$wk_datetime7)="Data e hora da sétima tentativa de contato: Contato bem sucedido? {wk_datetime7_yn}"
label(data$wk_datetime7_yn)="Contato bem sucedido?"
label(data$wk_datetime8)="Data e hora da oitava tentativa de contato: Contato bem sucedido? {wk_datetime8_yn}"
label(data$wk_datetime8_yn)="Contato bem sucedido?"
label(data$wk_datetime9)="Data e hora da nona tentativa de contato: Contato bem sucedido? {wk_datetime9_yn}"
label(data$wk_datetime9_yn)="Contato bem sucedido?"
label(data$wk_datetime10)="Data e hora da décima tentativa de contato: Contato bem sucedido? {wk_datetime10_yn}"
label(data$wk_datetime10_yn)="Contato bem sucedido?"
label(data$wk_safety)="Desde quando você começou a tomar as cápsulas, você teve algum sintoma novo que acredita que pode estar associado ao tratamento?"
label(data$wk_symptoms_note)="Por favor, descreva quais sintomas você teve"
label(data$wk_info1)="@DEFAULT=/ Início (dias):@HIDDENUsed in concatenation"
label(data$wk_start)="Os sintomas começaram há quantos dias?"
label(data$wk_info)="@DEFAULT=/ Severity: @HIDDEN  Used in concatenation "
label(data$wk_c120071)="Quanto os sintomas te incomodam em uma escala de 0 a 10?"
label(data$wk_c25471)="Os sintomas já se resolveram?"
label(data$wk_info_2)="@DEFAULT= há (dias): @HIDDEN  Used in concatenation "
label(data$wk_c178992)="Os sintomas se resolveram há quantos dias?"
label(data$wk_adherence)="Você tem tomado as cápsulas como foi orientado? (2 cápsulas no café da manhã, 2 no almoço e 2 no jantar, totalizando 6 cápsulas ao dia)"
label(data$wk_lostdose)="Na última semana você esqueceu alguma dose?"
label(data$wk_adherence_whyno)="Por que não?"
label(data$wk_question_yn)="Você tem alguma dúvida?"
label(data$wk_question_note)="Especifique as dúvidas"
label(data$wk_question_chk)="Dúvidas esclarecidas?"
label(data$pdf_survey)="PDF Upload of Survey Response"
label(data$contato_semanal_complete)="Complete?"
label(data$c25250)="O participante completou os 3 meses de intervenção?"
label(data$conclusion_date)="Data da Conclusão"
label(data$c66727)="Motivo da não conclusão"
label(data$conclusion_info)="   Ver explicações?    "
label(data$c66727_detail)="Detalhe:"
label(data$c66727_action)="Existe necessidade de alguma medida ética adicional?"
label(data$c66727_response)="Informações sobre medidas éticas adicionais"
label(data$concluso_complete)="Complete?"
label(data$attach_insertiondate)="Data em que está sendo inserido o arquivo"
label(data$attachment_type)="Selecione o tipo de anexo"
label(data$attach_filedate)="Data do documento"
label(data$attachment_other)="Especifique"
label(data$attachment_file)="Selecione o arquivo"
label(data$attachment_notes)="Data do documento {attachment_date} Selecione o arquivo para upload: {attachment_file}"
label(data$anexos_complete)="Complete?"